In [ ]:
import pandas as pd
import numpy as np

**Task 1 — Build your dataset as a list of tuples**

In [ ]:
ds = pd.read_csv("./credit_card_fraud.csv")
ds.sample(5)

#dataset loaded

,Transaction Date and Time,Transaction Amount,Cardholder Name,Card Number (Hashed or Encrypted),Merchant Name,Merchant Category Code (MCC),Transaction Location (City or ZIP Code),Transaction Currency,Card Type,Card Expiration Date,CVV Code (Hashed or Encrypted),Transaction Response Code,Transaction ID,Fraud Flag or Label,Previous Transactions,Transaction Source,IP Address,Device Information,User Account Information,Transaction Notes
2328,2021-06-17 21:38:59,996.29,Samar Virk,d01657c72eb0232bd87d32e931176c6bad8953a6a6537a...,Dixit-Sachdev,4861,Aizawl,USD,Visa,09/26,809e63d5c8aa03af112d17361058d0d8955f6d8e1e7591...,5,3bcccfa8-c167-4702-89e5-f4d5e27cc8cb,1,3 or more,Online,31.234.70.253,Tablet,umallick,Tempore placeat aliquid veritatis ad iusto dol...
6932,2020-06-20 21:39:42,4641.67,Shaan Dubey,8358f267a67ef2f3c619edec41a385cef03557b2b88440...,Konda and Sons,3487,Vellore,EUR,MasterCard,08/27,07e46896ba89f88776fed50a1b7895129f9b9af7d3b8b3...,5,af792ef6-946a-4307-a7e4-60682ece017b,1,1,In-Person,207.220.64.191,Mobile,ksane,Quod minima repellat.\nQui laudantium earum as...
6557,2023-01-08 19:37:12,4279.85,Yashvi Master,f0783604d1b5b568e5202d014e5ecd6eaf73a3050142fd...,Vig-Kaur,1228,Serampore,USD,American Express,03/27,8ebced264174028f8c5169d8787f7ff1ea2dc6d6c5a7a8...,12,9d7c1774-fb96-45bd-ad35-d2546292dba9,0,2,Online,216.140.154.170,Tablet,psrinivasan,Atque harum cum harum adipisci quisquam. Excep...
2235,2023-09-13 10:12:53,3511.63,Aarav Vyas,b04b52fe2b4dfffba7c24f35c119d585e01a9d58b8760f...,Karnik and Sons,7899,Satna,USD,American Express,09/27,c62510afc57db491f9f993387b76dd9a7d08f09c013269...,0,b66399e8-44a4-41cc-b2d8-0ec6a462aef8,1,1,Online,194.161.73.154,Tablet,NaN,Exercitationem necessitatibus doloribus aperia...
2397,2020-12-11 08:07:41,1227.78,Miraan Bali,d7b8d93bd2dc41d26439641b032055ddab0d40b551fa0a...,Tara-Shukla,9932,Nagaon,INR,Visa,11/29,5109a4e14cbbfda6b4512fc17ff13814ff9427f7b60269...,0,d56f1c5c-f370-4bcb-89ee-28a104582e5d,1,1,In-Person,165.247.99.95,Mobile,wmannan,Facere nesciunt incidunt aspernatur corporis q...

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 20 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Transaction Date and Time                8000 non-null   object
 1   Transaction Amount                       8000 non-null   float64
 2   Cardholder Name                          8000 non-null   object
 3   Card Number (Hashed or Encrypted)        8000 non-null   object
 4   Merchant Name                            8000 non-null   object
 5   Merchant Category Code (MCC)             8000 non-null   int64
 6   Transaction Location (City or ZIP Code)  8000 non-null   object
 7   Transaction Currency                     8000 non-null   object
 8   Card Type                                8000 non-null   object
 9   Card Expiration Date                     8000 non-null   object
 10  CVV Code (Hashed or Encrypted)           8000 non-null   object
 11  Transaction Response Code                8000 non-null   int64
 12  Transaction ID                           8000 non-null   object
 13  Fraud Flag or Label                      8000 non-null   int64
 14  Previous Transactions                    5957 non-null   object
 15  Transaction Source                       8000 non-null   object
 16  IP Address                               8000 non-null   object
 17  Device Information                       8000 non-null   object
 18  User Account Information                 3990 non-null   object
 19  Transaction Notes                        8000 non-null   object
dtypes: float64(1), int64(3), object(16)
memory usage: 1.2+ MB

In [ ]:
records = list(ds.itertuples(index=False))
display(records[:5])

[Pandas(_0='2022-09-24 13:54:27', _1=285.88, _2='Shray Soman', _3='daca51bffe0fc4eaaa7c430917f94b75fd8937124922549632bcd15afd89dc00', _4='Rajagopalan, Ghose and Kant', _5=3590, _6='Khammam', _7='INR', _8='MasterCard', _9='04/29', _10='01299ac65733b5a3d774265fbfe8396b8611e5e3321855dbc541cd301e71fe5e', _11=5, _12='b7f69cbc-a03d-41f8-adca-75920b0242c3', _13=1, _14=nan, _15='Online', _16='18.106.240.6', _17='Tablet', _18=nan, _19='Consequatur corporis minima ad vero deserunt nostrum. Laborum laudantium voluptatum porro dolorum.\nItaque ut quibusdam eius. Impedit at itaque assumenda ullam eaque.'),
 Pandas(_0='2020-07-24 11:20:13', _1=1777.32, _2='Lakshit Bakshi', _3='d5366dd9be3a0266c0252baceaa6332210ed4dbd0ef252a4e2f45707c290f4b4', _4='Sule PLC', _5=7277, _6='Vasai-Virar', _7='EUR', _8='American Express', _9='03/26', _10='ad8fa913d25b3970c6efa8ca504da8ba670ce2a9cf012d399b71924deb483d3f', _11=12, _12='ad53cc8e-8412-422e-8cad-4176daac8387', _13=1, _14=nan, _15='Online', _16='212.48.185.128', _17='Mobile', _18='jloyal', _19='Dolore repellendus odio deleniti. Eaque quibusdam nobis similique aperiam perferendis.\nIllo numquam earum at quidem rem est. Quis explicabo quasi quod sit accusamus.'),
 Pandas(_0='2023-03-18 01:05:36', _1=3939.01, _2='Riya Bobal', _3='4737a6384aa1c3c31f7768b86633d6a8401dd6ab4a8ff1f3c876a82830a98e57', _4='Badal PLC', _5=9297, _6='Nangloi Jat', _7='USD', _8='Visa', _9='11/29', _10='eb3be230bbd2844b1f5d8f2e4fab9ffba8ab22cfeeb69c4c1361993ba4f377b9', _11=5, _12='f09cecd6-0d74-4551-8089-a31d64e6b9c5', _13=1, _14='3 or more', _15='In-Person', _16='17.190.112.46', _17='Mobile', _18=nan, _19='Unde beatae perspiciatis sapiente. Voluptates magnam debitis facere officiis assumenda.\nDolorum nisi consequatur delectus sint dolor dolorum. Quae ullam nihil ullam.'),
 Pandas(_0='2021-01-07 21:53:04', _1=376.44, _2='Mohanlal Balakrishnan', _3='4721806eed8f2663bb597ff13e79a294de318358fbb54bcd4d282ef617d1fc67', _4='Konda-Sodhi', _5=5686, _6='Ramagundam', _7='USD', _8='Visa', _9='09/25', _10='891d46993a36d78392247c642138cede01d9841daab1d945709755b5194597c4', _11=5, _12='b208ae0b-4c4f-428f-b6b9-5360b288b947', _13=0, _14='2', _15='In-Person', _16='153.136.24.104', _17='Tablet', _18=nan, _19='Cupiditate repellendus necessitatibus quo occaecati. Maiores cupiditate doloribus. Eos voluptatum accusantium repellat. Fuga iste dolorum possimus cupiditate.\nEx quaerat unde quo velit alias animi.'),
 Pandas(_0='2021-12-16 06:22:24', _1=1687.33, _2='Mannat Rout', _3='9deacc3a9efd6e382826d400620aca5f23ed94327578e5cee370ce1278a99919', _4='Dua Ltd', _5=2940, _6='Adoni', _7='INR', _8='MasterCard', _9='03/31', _10='48a1a756f2d83f1dc57bbf14052b70a6f40d0fceed6662812e34903a9fe90924', _11=5, _12='6b4e4e43-5b73-4906-9973-299a1b2a5e71', _13=1, _14='2', _15='Online', _16='196.153.28.131', _17='Desktop', _18=nan, _19='Molestias assumenda consectetur itaque veritatis non vero. Sequi ipsa aliquam fugiat dolorem. Occaecati cum qui debitis nemo qui.')]

In [ ]:
cols = tuple(ds.columns)
cols

('Transaction Date and Time',
 'Transaction Amount',
 'Cardholder Name',
 'Card Number (Hashed or Encrypted)',
 'Merchant Name',
 'Merchant Category Code (MCC)',
 'Transaction Location (City or ZIP Code)',
 'Transaction Currency',
 'Card Type',
 'Card Expiration Date',
 'CVV Code (Hashed or Encrypted)',
 'Transaction Response Code',
 'Transaction ID',
 'Fraud Flag or Label',
 'Previous Transactions',
 'Transaction Source',
 'IP Address',
 'Device Information',
 'User Account Information',
 'Transaction Notes')

**How many records do you have? Confirm with len().**

In [ ]:
len(records)

8000

**Print the first and last record using indexing.**

In [ ]:
print(records[1],'\n',records[-1])

Pandas(_0='2020-07-24 11:20:13', _1=1777.32, _2='Lakshit Bakshi', _3='d5366dd9be3a0266c0252baceaa6332210ed4dbd0ef252a4e2f45707c290f4b4', _4='Sule PLC', _5=7277, _6='Vasai-Virar', _7='EUR', _8='American Express', _9='03/26', _10='ad8fa913d25b3970c6efa8ca504da8ba670ce2a9cf012d399b71924deb483d3f', _11=12, _12='ad53cc8e-8412-422e-8cad-4176daac8387', _13=1, _14=nan, _15='Online', _16='212.48.185.128', _17='Mobile', _18='jloyal', _19='Dolore repellendus odio deleniti. Eaque quibusdam nobis similique aperiam perferendis.\nIllo numquam earum at quidem rem est. Quis explicabo quasi quod sit accusamus.')
 Pandas(_0='2023-06-14 06:12:26', _1=3354.36, _2='Alia Bose', _3='8db138a97db4df2c7533dfca014dcd85c0385846a55e6cbd4310385c2dcc37a4', _4='Datta, Gandhi and Sha', _5=2902, _6='Dehradun', _7='INR', _8='Visa', _9='02/24', _10='c86a2932e1c79343a3c16fb218b9944791aaeedd3e30c87d1c7f505c0e588f7c', _11=12, _12='85588ac2-21c9-4c8d-a7fb-fd0d2b1fbb09', _13=0, _14='2', _15='In-Person', _16='159.232.79.67', _17='Mobile', _18='prishaghose', _19='Ipsa minus aperiam beatae. Iure dicta mollitia assumenda vel laudantium harum. Nulla culpa accusantium officia corrupti esse.')

**How many fields does each record have?**

In [ ]:
print(f"Each record has {len(cols)} fields.")

Each record has 20 fields.

**Loop through all records and print just two fields of your choice, using tuple unpacking.**

In [ ]:
print("Cardholder Name | Transaction Amount")
print("---------------------------------")

for i, record in enumerate(records):

    cardholder_name = record._2  # Corrected to Cardholder Name
    transaction_amount = record._1 # Corrected to Transaction Amount

    print(f"{cardholder_name:<17} | {transaction_amount:<18.2f}")
    if i >= len(records): # Print only the first 5 records for brevity
        break

Cardholder Name | Transaction Amount
---------------------------------
Shray Soman       | 285.88
Lakshit Bakshi    | 1777.32
Riya Bobal        | 3939.01
Mohanlal Balakrishnan | 376.44
Mannat Rout       | 1687.33
Lagan Dutt        | 3341.97
Neelofar Sangha   | 1212.14
Samiha Ravi       | 1117.52
Vihaan Walla      | 388.16
Ivan Loyal        | 4514.53
Hiran Subramaniam | 1805.22
Neysa Swaminathan | 2346.00
Ritvik Lall       | 453.19
Samar Sridhar     | 2538.36
Kiara Desai       | 4572.85
Tanya Khalsa      | 4172.21
Samiha Chauhan    | 1042.79
Sara Gala         | 907.46
Vihaan Lad        | 3347.31
Khushi Bhat       | 4014.63
Aaryahi Bhatnagar | 2971.68
Sana Bava         | 754.33
Taimur Ganesan    | 73.77
Anaya Tella       | 3006.39
Eshani Shankar    | 840.62
Biju Sekhon       | 4666.18
Rhea Sahota       | 2921.57
Kiara Yadav       | 4326.69
Vihaan Dhingra    | 1448.31
Yasmin Sarraf     | 2480.39
Nehmat Ram        | 923.31
Zeeshan Barad     | 2613.96
Kashvi Kothari    | 4525.17
Divij Kaur        | 4469.12
Nitara Tank       | 380.84
Kaira Borah       | 1052.74
Farhan Bahri      | 3633.43
Chirag Kashyap    | 120.89
Krish Rana        | 869.66
Vidur Agate       | 846.89
Zain Chopra       | 4432.28
Vihaan Randhawa   | 4801.36
Hiran Sem         | 441.26
Lavanya Aggarwal  | 1021.92
Vihaan Bhasin     | 2074.03
Madhup Sundaram   | 1352.51
Anika Gill        | 87.11
Dhruv Barman      | 268.18
Khushi Warrior    | 2058.95
Dhanush Sinha     | 3436.84
Aayush Lala       | 531.41
Sana Bajaj        | 350.56
Parinaaz Dube     | 1594.56
Hrishita Soni     | 1842.12
Mahika Chowdhury  | 230.10
Siya Ramakrishnan | 3752.75
Dharmajan Garg    | 1043.52
Raghav Dua        | 454.21
Neelofar Mangal   | 916.68
Zain Dugal        | 2873.36
Nitara Arora      | 3583.70
Aarna Wadhwa      | 4058.43
Shayak Swaminathan | 506.34
Ranbir Uppal      | 4993.49
Vivaan Thaman     | 2640.91
Ryan Kumer        | 2811.24
Samiha Balay      | 1869.35
Jiya Dube         | 194.52
Nayantara Grewal  | 2641.12
Rania Batta       | 2880.76
Dharmajan Dash    | 3464.75
Armaan Dar        | 4102.82
Amira Uppal       | 4875.85
Zeeshan Lalla     | 4788.09
Alisha Ravel      | 3407.84
Tiya Samra        | 300.66
Zaina Kothari     | 1081.58
Tanya Sachdeva    | 3254.81
Akarsh Chaudry    | 1755.95
Lagan Bali        | 1456.46
Yasmin Kumar      | 1385.76
Kavya Bhatti      | 3594.84
Jivika Rattan     | 3155.88
Mishti Mann       | 164.07
Samar Borah       | 4165.48
Misha Dube        | 2823.91
Anya Sur          | 1338.86
Nirvaan Baral     | 3721.86
Suhana Thaker     | 4146.54
Kartik Gara       | 2515.53
Onkar Dhingra     | 4088.07
Kanav Sood        | 113.91
Mahika Sangha     | 3663.65
Vardaniya Dhar    | 482.29
Yuvaan Sur        | 1310.13
Biju Tara         | 2303.18
Sahil Biswas      | 3414.18
Sahil Kapur       | 959.45
Nayantara Agarwal | 4484.69
Riya Dhaliwal     | 459.39
Oorja Rattan      | 405.03
Divyansh Lad      | 4549.77
Divij Yadav       | 2104.79
Pari Rout         | 1758.14
Dhanush Cheema    | 2861.40
Hridaan Mand      | 4259.91
Tejas Randhawa    | 4954.71
Ivan Krishnamurthy | 770.14
Zain Raju         | 374.72
Sahil Babu        | 3105.95
Anahita Ganguly   | 4565.66
Ira Srivastava    | 1230.56
Adah Shan         | 2660.60
Vardaniya Gill    | 2050.24
Vihaan Venkatesh  | 780.15
Rasha Babu        | 4650.63
Shaan Mammen      | 4288.98
Yakshit Rattan    | 2500.59
Dishani Ray       | 4697.86
Zeeshan Chaudhry  | 57.79
Ela Bhandari      | 2361.35
Faiyaz Iyengar    | 4036.39
Sara Borra        | 3559.53
Pari Gole         | 4946.62
Aniruddh Bala     | 4396.24
Rohan Gaba        | 1579.23
Indrans Chahal    | 1401.82
Samarth De        | 3442.08
Khushi Dora       | 2222.49
Chirag Lala       | 3421.90
Arnav Borra       | 4228.11
Jayant Madan      | 3906.68
Mishti Venkatesh  | 923.72
Madhup Ramaswamy  | 4196.15
Dhruv Wadhwa      | 3027.63
Samarth Bose      | 2876.61
Aradhya Hora      | 134.22
Devansh Kannan    | 4894.87
Dhanush Kaur      | 2349.24
Nayantara Gill    | 3416.20
Jivika Sarma      | 4666.44
Hazel Sani        | 1312.95
Jiya Bedi         | 2407.15
Piya D’Alia       | 3773.92
Vivaan Vig        | 4100.48
Kiara Gupta       | 4185.67
Onkar Som         | 4616.75
Tushar Divan      | 1447.42
Ayesha Ratti      | 2804.38
Darshit Dara      | 1318.95
Madhav Dey        | 3994.91
Inaaya  Tandon    | 4872.77
Misha Butala      | 3814.73
Miraya Ramaswamy  | 1744.56
Rasha Venkataraman | 4284.39
Miraan Uppal      | 4930.57
Myra Choudhry     | 3119.48
Vidur Upadhyay    | 79.71
Myra Chaudhari    | 2841.49
Onkar Buch        | 158.85
Ira Chaudhry      | 329.65
Priyansh Sahota   | 4765.70
Anika Brahmbhatt  | 3060.05
Pihu Kumar        | 409.12
Priyansh Kanda    | 2626.16
Kimaya Bhattacharyya | 761.04
Miraan Chahal     | 4576.97
Mohanlal Ramanathan | 4911.28
Urvi Karpe        | 839.98
Myra Kamdar       | 316.69
Renee Ghose       | 1808.56
Hiran Sule        | 193.03
Ayesha Krish      | 4985.57
Anya Sanghvi      | 3072.82
Armaan Contractor | 2211.87
Rohan Jayaraman   | 4650.87
Ranbir Saxena     | 1289.37
Rati Ramesh       | 396.19
Damini Mahajan    | 3629.67
Hunar Chokshi     | 1508.18
Riya Saran        | 4288.78
Charvi Banik      | 3830.63
Arnav Koshy       | 753.86
Onkar Sami        | 1454.48
Aaina Amble       | 801.82
Madhup Sarkar     | 4645.60
Akarsh Kala       | 236.27
Shamik Loyal      | 2200.69
Advik Chowdhury   | 1334.67
Anaya Sha         | 3049.15
Gokul Dutt        | 3603.95
Divyansh Cherian  | 3618.44
Nayantara Bhavsar | 4541.45
Farhan Raman      | 3737.84
Madhup Arora      | 454.72
Kiaan Chhabra     | 1793.26
Emir Varty        | 1910.55
Inaaya  Garg      | 963.63
Indrajit Gokhale  | 2359.92
Ishaan Mann       | 3581.55
Ayesha Sethi      | 2447.35
Saanvi Rastogi    | 4985.47
Amani Verma       | 3023.90
Yakshit Singhal   | 4783.38
Shamik Kumer      | 1.73
Saira Mannan      | 1251.74
Inaaya  Gour      | 58.59
Ira Hayer         | 1071.90
Purab Chacko      | 1335.21
Aarna Majumdar    | 1809.36
Stuvan Gade       | 2007.97
Shanaya Malhotra  | 3237.29
Divij Iyer        | 712.44
Miraya Gera       | 3075.03
Ivana Kapoor      | 1509.16
Yuvaan Manne      | 2641.00
Indranil Ranganathan | 2310.71
Lagan Manda       | 1721.63
Drishya Shetty    | 1802.52
Drishya Chaudhary | 1032.85
Nayantara Rama    | 4018.90
Nakul Wali        | 4736.28
Yuvaan Dhawan     | 4829.63
Lakshay Bakshi    | 3450.95
Aaina Babu        | 1663.79
Prisha Kala       | 2165.70
Nitya Choudhury   | 1192.09
Nitya Bhat        | 2563.94
Divit Bhatt       | 3793.77
Lakshay Dar       | 767.47
Gatik Thaker      | 970.27
Nehmat Zacharia   | 3073.27
Ishita Sahni      | 2957.64
Nirvi Loke        | 2791.89
Diya Sur          | 224.00
Armaan Mane       | 4703.78
Elakshi Sabharwal | 4139.41
Lavanya Chanda    | 1592.71
Arnav Sen         | 2435.34
Sumer Iyengar     | 625.73
Parinaaz Babu     | 1378.65
Anika Kata        | 1964.31
Anvi Srinivas     | 2516.13
Gatik Thaker      | 2058.35
Saksham Bawa      | 1582.93
Miraan Jani       | 4973.16
Nehmat Sharaf     | 3551.68
Jivin Sanghvi     | 2860.58
Alisha Mani       | 4608.68
Lakshit Krishnan  | 2716.93
Azad Bali         | 2677.18
Madhav Kapadia    | 832.95
Amira Mannan      | 4657.43
Reyansh Sant      | 3711.06
Diya Bava         | 157.67
Tanya Brar        | 217.36
Hrishita Randhawa | 2313.04
Hiran Bahl        | 4957.54
Seher Sanghvi     | 2210.17
Kimaya Ghose      | 3742.78
Siya Gola         | 1947.47
Priyansh Shukla   | 4938.86
Hrishita Dhar     | 273.50
Himmat Tara       | 1818.33
Reyansh Atwal     | 2280.73
Ela Singhal       | 1480.45
Nitara Soman      | 801.64
Sara Ghose        | 11.77
Kimaya Borde      | 1944.84
Himmat Chaudhari  | 4420.33
Sara Shere        | 339.86
Khushi Zachariah  | 4163.29
Sara Bains        | 3860.00
Yasmin Dube       | 4118.94
Dhanuk Warrior    | 1466.93
Shamik Chokshi    | 1469.43
Abram Mandal      | 2015.48
Emir Garde        | 4008.75
Ivana Mand        | 4562.07
Prerak Khanna     | 213.30
Kaira Bahl        | 3240.10
Saira Ravel       | 2247.67
Saksham Bhasin    | 4140.95
Divij Sekhon      | 3371.38
Seher Chada       | 3910.10
Shamik Wagle      | 1557.70
Jayant Saini      | 4856.13
Himmat Sura       | 434.53
Abram Dasgupta    | 386.36
Aarav Handa       | 3469.69
Saanvi Dey        | 3472.64
Aaryahi Dora      | 2076.68
Armaan Dutta      | 1780.45
Shayak Kala       | 4034.96
Nishith Walia     | 3705.92
Lavanya Dayal     | 1896.74
Mahika Verma      | 897.86
Khushi Samra      | 3955.06
Keya Mammen       | 2755.36
Samaira Dora      | 4584.73
Uthkarsh Soman    | 4155.78
Emir Dhawan       | 3833.05
Aayush Bahri      | 4922.33
Vritika Bhasin    | 3474.28
Anika Ratta       | 2196.18
Gokul Sama        | 3923.83
Sana Bali         | 496.71
Advik Kakar       | 1384.24
Vardaniya Gala    | 2595.70
Saksham Master    | 1213.86
Vritika Barad     | 1882.24
Aaina Gulati      | 1830.68
Mohanlal Karan    | 435.76
Priyansh Sharma   | 2325.80
Tanya Mannan      | 4975.46
Arnav Ramanathan  | 2499.98
Ehsaan Malhotra   | 23.75
Ryan Halder       | 2727.83
Krish Sheth       | 4569.84
Kanav Goda        | 3513.63
Alia Dora         | 1197.84
Arnav Kota        | 2943.83
Ishita Deshpande  | 4248.64
Navya Anand       | 2639.65
Dhanush Bala      | 3012.79
Shayak Kadakia    | 2756.46
Tiya Kade         | 2819.11
Veer Ray          | 131.98
Pranay Warrior    | 214.43
Dhanuk Singh      | 1963.23
Sana Chatterjee   | 3892.21
Aayush Das        | 1179.89
Baiju Mander      | 1765.96
Adira Soman       | 2407.40
Lakshay Gokhale   | 4622.82
Ivan Aggarwal     | 2914.16
Pranay Magar      | 3659.49
Yakshit Bedi      | 2825.44
Bhavin Brar       | 3191.20
Saksham Dani      | 2945.52
Anaya Brahmbhatt  | 4656.50
Yuvaan Vaidya     | 3819.82
Raunak Sundaram   | 3798.93
Parinaaz Ravel    | 946.03
Rohan Hayer       | 813.79
Divij Lal         | 3805.16
Kavya Sundaram    | 382.39
Priyansh Hayre    | 365.58
Kiaan Anand       | 3757.13
Shayak Saran      | 855.76
Amani Tailor      | 4474.64
Purab Karpe       | 1637.04
Aaryahi Ahluwalia | 3316.02
Adira Ghosh       | 4026.87
Umang Hayre       | 1920.92
Drishya Vaidya    | 734.34
Rania Deshpande   | 4279.74
Anya Kohli        | 159.94
Ryan Bumb         | 2962.00
Arhaan Ghosh      | 4666.59
Eva Raval         | 4427.25
Lakshay Bobal     | 4642.25
Veer Mander       | 369.54
Mahika Batra      | 4280.93
Neelofar Sibal    | 4776.58
Amira Venkataraman | 3673.06
Nirvi Ratti       | 325.78
Biju Soman        | 2484.35
Amani Wali        | 4772.71
Yakshit Goel      | 489.77
Zoya Garg         | 383.77
Stuvan Ravi       | 3705.48
Nirvi Chakrabarti | 693.85
Elakshi Doshi     | 1690.86
Mahika Bahl       | 238.23
Yakshit Chander   | 1938.72
Samarth Sangha    | 4481.87
Mishti Das        | 4919.04
Saksham Bahl      | 4820.70
Manikya Bumb      | 4960.79
Rhea Boase        | 2750.47
Aarna Wable       | 4953.60
Ela Kumer         | 2317.53
Vedika Tiwari     | 3867.39
Lakshay Ghose     | 2414.29
Armaan Comar      | 3815.85
Purab Sarin       | 4289.08
Mannat Ganesan    | 1278.35
Zara Dixit        | 2437.41
Devansh Sharaf    | 4071.30
Nayantara Dhaliwal | 4771.50
Vivaan Ravi       | 2725.52
Anay Lad          | 3386.74
Suhana Chaudhry   | 2914.89
Kavya Sundaram    | 3354.62
Manikya Ghose     | 3401.42
Taran Deep        | 3669.58
Anahita Kale      | 4613.40
Inaaya  Boase     | 2022.56
Badal Dasgupta    | 2360.63
Miraya Soni       | 221.17
Sumer Sane        | 1815.61
Fateh Kapadia     | 3412.71
Madhav Dara       | 1481.64
Ranbir Agate      | 3819.96
Anaya Chaudhuri   | 400.83
Dishani Banerjee  | 1424.50
Riya Karnik       | 3309.84
Zeeshan Acharya   | 4283.55
Taran Sami        | 2712.40
Darshit Sani      | 1946.59
Ivan Mahajan      | 124.26
Zaina Chakraborty | 2012.12
Mannat Arora      | 1096.55
Gatik Sethi       | 3726.60
Reyansh Divan     | 2481.82
Kiaan Bhatti      | 1366.98
Miraan Bera       | 1932.08
Priyansh Verma    | 1931.76
Arhaan Mangal     | 428.49
Miraan Warrior    | 1639.89
Anya Gupta        | 503.60
Divyansh Shukla   | 758.62
Ishaan Verma      | 3685.06
Bhavin Ben        | 4321.98
Ryan Choudhry     | 3166.64
Oorja Bhatti      | 3276.62
Hazel Lad         | 4845.42
Riya Kala         | 3609.01
Biju Dugar        | 4686.24
Arhaan Kar        | 4343.00
Shamik Kanda      | 2227.95
Riya Rajagopal    | 2128.11
Vivaan Kaul       | 2594.02
Ritvik Bandi      | 1445.31
Shlok Saraf       | 365.55
Jiya Vora         | 4989.22
Yuvraj  Maharaj   | 4039.48
Farhan Malhotra   | 3148.95
Priyansh Baria    | 4405.11
Miraya Dutt       | 4168.97
Tanya Singhal     | 4741.39
Shamik Batra      | 4112.28
Jiya Sarkar       | 1261.09
Parinaaz Dyal     | 35.43
Drishya Ray       | 3993.69
Elakshi Dasgupta  | 2553.71
Keya Toor         | 2111.80
Anya Shanker      | 3240.35
Kabir Krishna     | 2920.24
Yuvraj  Dash      | 778.61
Adah Keer         | 1304.09
Divij Basu        | 4321.72
Shanaya Baral     | 4518.03
Amani Sant        | 2101.83
Vaibhav Dugal     | 1357.95
Kaira Arya        | 2201.88
Manikya Bhat      | 3802.98
Trisha Saha       | 2230.60
Kabir Acharya     | 3235.53
Samaira Chandra   | 590.80
Parinaaz Date     | 70.48
Taimur Sarna      | 3983.88
Sara Bala         | 4916.21
Adah Deshpande    | 4290.78
Neelofar Wagle    | 2549.58
Miraan Upadhyay   | 3995.02
Ayesha Chad       | 4201.30
Nitara Kaur       | 3260.70
Samiha Tak        | 4981.82
Raunak Ramachandran | 4135.98
Purab Jaggi       | 1395.97
Neysa Bains       | 1637.79
Anaya Dora        | 858.91
Bhamini Solanki   | 1119.42
Eshani Ravi       | 3261.51
Seher Kakar       | 2780.85
Divij Rout        | 4315.21
Veer Dalal        | 73.27
Divit Aurora      | 3741.54
Ayesha Aurora     | 4463.23
Misha Trivedi     | 4745.09
Aaina Hayre       | 797.51
Piya Shan         | 1336.19
Parinaaz Jaggi    | 3022.27
Nirvaan Dey       | 209.02
Sumer Sharma      | 582.36
Vedika Mammen     | 57.13
Kaira Rattan      | 2871.45
Aarav Bava        | 3039.62
Mahika Vohra      | 760.41
Prisha Warrior    | 3283.05
Prerak Virk       | 224.73
Samarth Kulkarni  | 4050.93
Jivin Loyal       | 2089.36
Riya Ghose        | 4033.65
Fateh Bir         | 2298.61
Emir Bala         | 2850.71
Misha Srinivasan  | 516.44
Ela Chaudhuri     | 335.61
Charvi Kari       | 4925.60
Anvi Tripathi     | 1141.58
Shlok Tella       | 4241.67
Misha Mall        | 1233.47
Shalv Johal       | 2012.85
Zain Subramaniam  | 1757.41
Samarth Aggarwal  | 3265.76
Shaan Chokshi     | 2790.25
Yakshit Kapadia   | 1155.31
Ojas Dhillon      | 3115.79
Uthkarsh Wali     | 171.38
Mahika Batta      | 2840.21
Ritvik Rana       | 795.65
Yuvaan Tandon     | 769.35
Vedika Virk       | 3946.83
Nishith Badal     | 96.91
Damini Zacharia   | 2514.09
Indrans Raj       | 4011.03
Parinaaz Dey      | 4959.80
Piya Sengupta     | 2015.87
Pari Kadakia      | 98.04
Miraan Saha       | 2017.61
Anvi Rao          | 1493.58
Ayesha Andra      | 890.16
Nishith Seth      | 2067.78
Lavanya Dhar      | 1972.50
Aaina Kashyap     | 1149.53
Tara Comar        | 1197.75
Sahil Agarwal     | 2763.82
Nirvi Dhawan      | 1896.51
Veer Mander       | 3197.10
Sumer Bhavsar     | 1130.91
Jayan Dasgupta    | 2052.55
Ela Hora          | 4629.67
Aaryahi Dutt      | 3417.69
Charvi Bhakta     | 173.19
Farhan Bhardwaj   | 2685.65
Divyansh Wagle    | 4170.62
Baiju Sanghvi     | 2377.67
Khushi Kala       | 4361.83
Advik Bansal      | 1471.64
Seher Choudhury   | 3613.86
Bhamini Saraf     | 591.60
Veer Kapadia      | 728.51
Hansh Krishnan    | 3548.38
Ivana Agrawal     | 4133.38
Aaina Subramaniam | 3334.64
Tarini Lal        | 3691.72
Kabir Sahota      | 1813.01
Reyansh Kakar     | 2792.85
Rohan Balakrishnan | 2853.15
Kanav Ranganathan | 4745.75
Trisha Date       | 118.98
Divit Kumer       | 1767.78
Romil Sathe       | 4430.14
Siya Agate        | 1671.31
Dhanuk Maharaj    | 4527.29
Neelofar Swamy    | 1700.45
Arhaan Ravi       | 1455.60
Bhavin Bansal     | 433.22
Priyansh Shah     | 2526.08
Dhanush Din       | 2595.66
Jhanvi Mahajan    | 546.27
Ela Jain          | 3751.88
Taimur Varty      | 101.16
Baiju Sagar       | 4292.86
Nitara Sha        | 865.32
Hrishita Basak    | 902.89
Vihaan Edwin      | 3685.52
Neelofar Goel     | 579.70
Oorja Bahl        | 1716.74
Faiyaz Singh      | 2593.18
Baiju Chowdhury   | 14.24
Yasmin Bhardwaj   | 3386.72
Shalv Dhawan      | 4644.45
Bhamini Ramesh    | 4827.35
Mamooty Kar       | 4390.23
Raunak Sekhon     | 4525.51
Samarth Tandon    | 3676.42
Mannat Kibe       | 48.76
Arhaan Kata       | 304.80
Kanav Garg        | 672.97
Aaryahi Date      | 1623.18
Vivaan Seth       | 3515.03
Trisha Sule       | 3850.24
Khushi Sheth      | 4599.41
Renee Bhattacharyya | 4088.20
Ojas Sarraf       | 4347.45
Myra Gandhi       | 512.02
Oorja Balan       | 1371.58
Keya Chawla       | 1954.63
Ayesha Rao        | 4597.33
Divyansh Sama     | 4018.11
Sara Dora         | 1552.53
Sana Mander       | 2330.37
Farhan Kumer      | 2067.67
Nirvi Sodhi       | 55.41
Nitya Sachdeva    | 2477.92
Adira Gola        | 1604.26
Nayantara Johal   | 2485.72
Sahil Lad         | 2988.66
Vidur Guha        | 3323.11
Samarth Konda     | 352.87
Mamooty Chaudhuri | 3510.30
Vritika Dubey     | 4328.79
Kiara Handa       | 3237.41
Vardaniya Som     | 4156.48
Jayant Master     | 1674.42
Khushi Goda       | 4303.43
Sara Babu         | 521.74
Anay Dutta        | 4097.11
Mamooty Subramaniam | 351.40
Uthkarsh Lalla    | 3149.37
Advik Guha        | 560.52
Seher Shukla      | 2652.36
Rasha Sawhney     | 654.55
Kanav Kapadia     | 4078.66
Khushi Sem        | 1748.05
Jivika Jani       | 4448.20
Bhamini Balay     | 1482.27
Zoya Ranganathan  | 3790.83
Mehul Mangal      | 1995.24
Renee Sundaram    | 1504.79
Shaan Rajagopalan | 2302.47
Jhanvi Chadha     | 4344.77
Pranay Rama       | 897.81
Vihaan Vala       | 1280.47
Alisha Tara       | 504.67
Dhruv Hari        | 1268.27
Shanaya Gole      | 1173.25
Siya Bir          | 1853.29
Nitara Wali       | 162.04
Ivan Sama         | 4519.00
Tiya Chahal       | 463.51
Rati Sarraf       | 4089.78
Ela Devi          | 1310.39
Stuvan Reddy      | 2521.66
Urvi Jha          | 4993.59
Jivin Sankaran    | 3823.43
Myra Setty        | 4460.78
Divij Dhar        | 2670.03
Tarini Dara       | 1296.52
Parinaaz Jaggi    | 3571.33
Aradhya Varghese  | 4413.20
Zaina Khare       | 3454.05
Anahi Chanda      | 4573.08
Ryan Handa        | 528.83
Urvi Sachdeva     | 2734.53
Vedika Datta      | 4612.85
Shlok Ray         | 3306.32
Sahil Ganesan     | 1900.93
Anahi Malhotra    | 767.66
Kiara Raval       | 954.31
Yashvi Khosla     | 1932.47
Anya Upadhyay     | 2372.98
Fateh Raval       | 4951.13
Alia Shukla       | 672.63
Priyansh Desai    | 1639.44
Alisha Raju       | 1723.17
Devansh Bobal     | 2477.12
Ojas Datta        | 3139.28
Aarna Chaudhari   | 2518.67
Nitya Choudhry    | 3844.06
Anahita Kalla     | 2492.50
Indranil Bains    | 55.33
Saksham Sampath   | 3055.58
Aarna Gala        | 1680.42
Indrajit Borra    | 2434.46
Rati Gaba         | 3232.62
Damini Wadhwa     | 3452.40
Elakshi Ahluwalia | 1116.68
Lavanya Mammen    | 2181.90
Vihaan Sood       | 1863.68
Amani Kumer       | 1576.11
Dhruv Kaul        | 211.31
Rohan Subramanian | 418.42
Faiyaz Warrior    | 764.23
Yashvi Singh      | 3401.78
Parinaaz Lalla    | 593.54
Samiha Lanka      | 3118.83
Vritika Shroff    | 2567.77
Madhup Sehgal     | 4146.15
Anahita Seshadri  | 1286.24
Anika Wali        | 4305.99
Kiaan Brar        | 975.00
Ishita Ratti      | 4260.06
Kashvi Joshi      | 4191.48
Pari Raja         | 1536.38
Nayantara Chatterjee | 3389.54
Vidur Sood        | 575.38
Sahil Subramaniam | 4044.47
Vidur Lalla       | 3394.73
Mehul Sawhney     | 1182.93
Navya Varma       | 4597.43
Vihaan Behl       | 3516.48
Saksham Doctor    | 586.60
Romil Kapadia     | 1970.33
Inaaya  Sandhu    | 3306.58
Samar Sachdeva    | 1066.25
Zeeshan Taneja    | 1489.72
Divit Kohli       | 118.69
Charvi Mandal     | 2151.00
Nirvaan Bumb      | 3942.32
Ela Krishnamurthy | 831.35
Alisha Kakar      | 4791.57
Eva Mani          | 1236.56
Mehul Wali        | 3338.55
Onkar Sani        | 3674.23
Shamik Taneja     | 3739.47
Jivika Singh      | 3549.65
Jayant Thakur     | 2617.00
Shaan Savant      | 2040.83
Mannat Wason      | 4302.43
Nitya Ahuja       | 3539.34
Bhamini Chandra   | 2314.15
Aayush Baral      | 1090.36

# **Task 2 — Slice your dataset like a data scientist**

**Select the first 3 records (imagine this as a "training split").**

In [ ]:
records[0:3]

,Transaction Date and Time,Transaction Amount,Cardholder Name,Card Number (Hashed or Encrypted),Merchant Name,Merchant Category Code (MCC),Transaction Location (City or ZIP Code),Transaction Currency,Card Type,Card Expiration Date,CVV Code (Hashed or Encrypted),Transaction Response Code,Transaction ID,Fraud Flag or Label,Previous Transactions,Transaction Source,IP Address,Device Information,User Account Information,Transaction Notes
0,2022-09-24 13:54:27,285.88,Shray Soman,daca51bffe0fc4eaaa7c430917f94b75fd893712492254...,"Rajagopalan, Ghose and Kant",3590,Khammam,INR,MasterCard,04/29,01299ac65733b5a3d774265fbfe8396b8611e5e3321855...,5,b7f69cbc-a03d-41f8-adca-75920b0242c3,1,NaN,Online,18.106.240.6,Tablet,NaN,Consequatur corporis minima ad vero deserunt n...
1,2020-07-24 11:20:13,1777.32,Lakshit Bakshi,d5366dd9be3a0266c0252baceaa6332210ed4dbd0ef252...,Sule PLC,7277,Vasai-Virar,EUR,American Express,03/26,ad8fa913d25b3970c6efa8ca504da8ba670ce2a9cf012d...,12,ad53cc8e-8412-422e-8cad-4176daac8387,1,NaN,Online,212.48.185.128,Mobile,jloyal,Dolore repellendus odio deleniti. Eaque quibus...
2,2023-03-18 01:05:36,3939.01,Riya Bobal,4737a6384aa1c3c31f7768b86633d6a8401dd6ab4a8ff1...,Badal PLC,9297,Nangloi Jat,USD,Visa,11/29,eb3be230bbd2844b1f5d8f2e4fab9ffba8ab22cfeeb69c...,5,f09cecd6-0d74-4551-8089-a31d64e6b9c5,1,3 or more,In-Person,17.190.112.46,Mobile,NaN,Unde beatae perspiciatis sapiente. Voluptates ...

**Select the last 2 records (a "test split").**

In [ ]:
records[-2:]

[Pandas(Index=7998, _1='2021-05-16 18:21:52', _2=3035.31, _3='Chirag Rege', _4='669bd9fcc7e40cc25d99c773678e48bcb3fdadf7fee6a9b735952b431c96d51f', _5='Kakar LLC', _6=4015, _7='Sultan Pur Majra', _8='EUR', _9='American Express', _10='09/24', _11='e7866fdc6672f827c76f6124ca3eeaff44aff8b7caf4ee1469b2ab887e7e7875', _12=0, _13='2424f724-8bd2-4dd0-8b39-e824999a9764', _14=1, _15='1', _16='In-Person', _17='216.56.133.227', _18='Tablet', _19='sumeriyengar', _20='Animi excepturi nam distinctio fuga. Vel eius praesentium itaque.'),
 Pandas(Index=7999, _1='2023-06-14 06:12:26', _2=3354.36, _3='Alia Bose', _4='8db138a97db4df2c7533dfca014dcd85c0385846a55e6cbd4310385c2dcc37a4', _5='Datta, Gandhi and Sha', _6=2902, _7='Dehradun', _8='INR', _9='Visa', _10='02/24', _11='c86a2932e1c79343a3c16fb218b9944791aaeedd3e30c87d1c7f505c0e588f7c', _12=12, _13='85588ac2-21c9-4c8d-a7fb-fd0d2b1fbb09', _14=0, _15='2', _16='In-Person', _17='159.232.79.67', _18='Mobile', _19='prishaghose', _20='Ipsa minus aperiam beatae. Iure dicta mollitia assumenda vel laudantium harum. Nulla culpa accusantium officia corrupti esse.')]

**Select every other record using step slicing.**

In [ ]:
records[::2]

**From any one record, extract only the numeric fields using tuple slicing or indexing.**

In [ ]:

first_record = records[0]


transaction_amount = first_record._2
mcc = first_record._6
transaction_response_code = first_record._12
fraud_flag = first_record._14
previous_transactions = first_record._15

print(f"Transaction Amount: {transaction_amount}")
print(f"Merchant Category Code (MCC): {mcc}")
print(f"Transaction Response Code: {transaction_response_code}")
print(f"Fraud Flag or Label: {fraud_flag}")
print(f"Previous Transactions: {previous_transactions}")


numeric_fields = (
    first_record._2,
    first_record._6,
    first_record._12,
    first_record._14,
    first_record._15
)

print(f"\nAll numeric fields from the first record: {numeric_fields}")

Transaction Amount: 285.88
Merchant Category Code (MCC): 3590
Transaction Response Code: 5
Fraud Flag or Label: 1
Previous Transactions: nan

All numeric fields from the first record: (285.88, 3590, 5, 1, nan)

# **Task 3 — Turn your dataset into a dictionary (Mappings)**

**Print one record's value for a specific field by name, e.g. named_records[0]["your_field"]**

In [ ]:
r= records[1]
d= dict(zip(cols,r))
def to_record(row):
  return dict(zip(cols,row))

named_red=[to_record(r) for r in records]
ex=named_red[-2]['Transaction Date and Time']

In [ ]:
list1=[]
for i in named_red:
  if i[ 'Cardholder Name'] not in list1:
    list1.append(i[ 'Cardholder Name'])
list1

['Shray Soman',
 'Lakshit Bakshi',
 'Riya Bobal',
 'Mohanlal Balakrishnan',
 'Mannat Rout',
 'Lagan Dutt',
 'Neelofar Sangha',
 'Samiha Ravi',
 'Vihaan Walla',
 'Ivan Loyal',
 'Hiran Subramaniam',
 'Neysa Swaminathan',
 'Ritvik Lall',
 'Samar Sridhar',
 'Kiara Desai',
 'Tanya Khalsa',
 'Samiha Chauhan',
 'Sara Gala',
 'Vihaan Lad',
 'Khushi Bhat',
 'Aaryahi Bhatnagar',
 'Sana Bava',
 'Taimur Ganesan',
 'Anaya Tella',
 'Eshani Shankar',
 'Biju Sekhon',
 'Rhea Sahota',
 'Kiara Yadav',
 'Vihaan Dhingra',
 'Yasmin Sarraf',
 'Nehmat Ram',
 'Zeeshan Barad',
 'Kashvi Kothari',
 'Divij Kaur',
 'Nitara Tank',
 'Kaira Borah',
 'Farhan Bahri',
 'Chirag Kashyap',
 'Krish Rana',
 'Vidur Agate',
 'Zain Chopra',
 'Vihaan Randhawa',
 'Hiran Sem',
 'Lavanya Aggarwal',
 'Vihaan Bhasin',
 'Madhup Sundaram',
 'Anika Gill',
 'Dhruv Barman',
 'Khushi Warrior',
 'Dhanush Sinha',
 'Aayush Lala',
 'Sana Bajaj',
 'Parinaaz Dube',
 'Hrishita Soni',
 'Mahika Chowdhury',
 'Siya Ramakrishnan',
 'Dharmajan Garg',
 'Raghav Dua',
 'Neelofar Mangal',
 'Zain Dugal',
 'Nitara Arora',
 'Aarna Wadhwa',
 'Shayak Swaminathan',
 'Ranbir Uppal',
 'Vivaan Thaman',
 'Ryan Kumer',
 'Samiha Balay',
 'Jiya Dube',
 'Nayantara Grewal',
 'Rania Batta',
 'Dharmajan Dash',
 'Armaan Dar',
 'Amira Uppal',
 'Zeeshan Lalla',
 'Alisha Ravel',
 'Tiya Samra',
 'Zaina Kothari',
 'Tanya Sachdeva',
 'Akarsh Chaudry',
 'Lagan Bali',
 'Yasmin Kumar',
 'Kavya Bhatti',
 'Jivika Rattan',
 'Mishti Mann',
 'Samar Borah',
 'Misha Dube',
 'Anya Sur',
 'Nirvaan Baral',
 'Suhana Thaker',
 'Kartik Gara',
 'Onkar Dhingra',
 'Kanav Sood',
 'Mahika Sangha',
 'Vardaniya Dhar',
 'Yuvaan Sur',
 'Biju Tara',
 'Sahil Biswas',
 'Sahil Kapur',
 'Nayantara Agarwal',
 'Riya Dhaliwal',
 'Oorja Rattan',
 'Divyansh Lad',
 'Divij Yadav',
 'Pari Rout',
 'Dhanush Cheema',
 'Hridaan Mand',
 'Tejas Randhawa',
 'Ivan Krishnamurthy',
 'Zain Raju',
 'Sahil Babu',
 'Anahita Ganguly',
 'Ira Srivastava',
 'Adah Shan',
 'Vardaniya Gill',
 'Vihaan Venkatesh',
 'Rasha Babu',
 'Shaan Mammen',
 'Yakshit Rattan',
 'Dishani Ray',
 'Zeeshan Chaudhry',
 'Ela Bhandari',
 'Faiyaz Iyengar',
 'Sara Borra',
 'Pari Gole',
 'Aniruddh Bala',
 'Rohan Gaba',
 'Indrans Chahal',
 'Samarth De',
 'Khushi Dora',
 'Chirag Lala',
 'Arnav Borra',
 'Jayant Madan',
 'Mishti Venkatesh',
 'Madhup Ramaswamy',
 'Dhruv Wadhwa',
 'Samarth Bose',
 'Aradhya Hora',
 'Devansh Kannan',
 'Dhanush Kaur',
 'Nayantara Gill',
 'Jivika Sarma',
 'Hazel Sani',
 'Jiya Bedi',
 'Piya D’Alia',
 'Vivaan Vig',
 'Kiara Gupta',
 'Onkar Som',
 'Tushar Divan',
 'Ayesha Ratti',
 'Darshit Dara',
 'Madhav Dey',
 'Inaaya  Tandon',
 'Misha Butala',
 'Miraya Ramaswamy',
 'Rasha Venkataraman',
 'Miraan Uppal',
 'Myra Choudhry',
 'Vidur Upadhyay',
 'Myra Chaudhari',
 'Onkar Buch',
 'Ira Chaudhry',
 'Priyansh Sahota',
 'Anika Brahmbhatt',
 'Pihu Kumar',
 'Priyansh Kanda',
 'Kimaya Bhattacharyya',
 'Miraan Chahal',
 'Mohanlal Ramanathan',
 'Urvi Karpe',
 'Myra Kamdar',
 'Renee Ghose',
 'Hiran Sule',
 'Ayesha Krish',
 'Anya Sanghvi',
 'Armaan Contractor',
 'Rohan Jayaraman',
 'Ranbir Saxena',
 'Rati Ramesh',
 'Damini Mahajan',
 'Hunar Chokshi',
 'Riya Saran',
 'Charvi Banik',
 'Arnav Koshy',
 'Onkar Sami',
 'Aaina Amble',
 'Madhup Sarkar',
 'Akarsh Kala',
 'Shamik Loyal',
 'Advik Chowdhury',
 'Anaya Sha',
 'Gokul Dutt',
 'Divyansh Cherian',
 'Nayantara Bhavsar',
 'Farhan Raman',
 'Madhup Arora',
 'Kiaan Chhabra',
 'Emir Varty',
 'Inaaya  Garg',
 'Indrajit Gokhale',
 'Ishaan Mann',
 'Ayesha Sethi',
 'Saanvi Rastogi',
 'Amani Verma',
 'Yakshit Singhal',
 'Shamik Kumer',
 'Saira Mannan',
 'Inaaya  Gour',
 'Ira Hayer',
 'Purab Chacko',
 'Aarna Majumdar',
 'Stuvan Gade',
 'Shanaya Malhotra',
 'Divij Iyer',
 'Miraya Gera',
 'Ivana Kapoor',
 'Yuvaan Manne',
 'Indranil Ranganathan',
 'Lagan Manda',
 'Drishya Shetty',
 'Drishya Chaudhary',
 'Nayantara Rama',
 'Nakul Wali',
 'Yuvaan Dhawan',
 'Lakshay Bakshi',
 'Aaina Babu',
 'Prisha Kala',
 'Nitya Choudhury',
 'Nitya Bhat',
 'Divit Bhatt',
 'Lakshay Dar',
 'Gatik Thaker',
 'Nehmat Zacharia',
 'Ishita Sahni',
 'Nirvi Loke',
 'Diya Sur',
 'Armaan Mane',
 'Elakshi Sabharwal',
 'Lavanya Chanda',
 'Arnav Sen',
 'Sumer Iyengar',
 'Parinaaz Babu',
 'Anika Kata',
 'Anvi Srinivas',
 'Saksham Bawa',
 'Miraan Jani',
 'Nehmat Sharaf',
 'Jivin Sanghvi',
 'Alisha Mani',
 'Lakshit Krishnan',
 'Azad Bali',
 'Madhav Kapadia',
 'Amira Mannan',
 'Reyansh Sant',
 'Diya Bava',
 'Tanya Brar',
 'Hrishita Randhawa',
 'Hiran Bahl',
 'Seher Sanghvi',
 'Kimaya Ghose',
 'Siya Gola',
 'Priyansh Shukla',
 'Hrishita Dhar',
 'Himmat Tara',
 'Reyansh Atwal',
 'Ela Singhal',
 'Nitara Soman',
 'Sara Ghose',
 'Kimaya Borde',
 'Himmat Chaudhari',
 'Sara Shere',
 'Khushi Zachariah',
 'Sara Bains',
 'Yasmin Dube',
 'Dhanuk Warrior',
 'Shamik Chokshi',
 'Abram Mandal',
 'Emir Garde',
 'Ivana Mand',
 'Prerak Khanna',
 'Kaira Bahl',
 'Saira Ravel',
 'Saksham Bhasin',
 'Divij Sekhon',
 'Seher Chada',
 'Shamik Wagle',
 'Jayant Saini',
 'Himmat Sura',
 'Abram Dasgupta',
 'Aarav Handa',
 'Saanvi Dey',
 'Aaryahi Dora',
 'Armaan Dutta',
 'Shayak Kala',
 'Nishith Walia',
 'Lavanya Dayal',
 'Mahika Verma',
 'Khushi Samra',
 'Keya Mammen',
 'Samaira Dora',
 'Uthkarsh Soman',
 'Emir Dhawan',
 'Aayush Bahri',
 'Vritika Bhasin',
 'Anika Ratta',
 'Gokul Sama',
 'Sana Bali',
 'Advik Kakar',
 'Vardaniya Gala',
 'Saksham Master',
 'Vritika Barad',
 'Aaina Gulati',
 'Mohanlal Karan',
 'Priyansh Sharma',
 'Tanya Mannan',
 'Arnav Ramanathan',
 'Ehsaan Malhotra',
 'Ryan Halder',
 'Krish Sheth',
 'Kanav Goda',
 'Alia Dora',
 'Arnav Kota',
 'Ishita Deshpande',
 'Navya Anand',
 'Dhanush Bala',
 'Shayak Kadakia',
 'Tiya Kade',
 'Veer Ray',
 'Pranay Warrior',
 'Dhanuk Singh',
 'Sana Chatterjee',
 'Aayush Das',
 'Baiju Mander',
 'Adira Soman',
 'Lakshay Gokhale',
 'Ivan Aggarwal',
 'Pranay Magar',
 'Yakshit Bedi',
 'Bhavin Brar',
 'Saksham Dani',
 'Anaya Brahmbhatt',
 'Yuvaan Vaidya',
 'Raunak Sundaram',
 'Parinaaz Ravel',
 'Rohan Hayer',
 'Divij Lal',
 'Kavya Sundaram',
 'Priyansh Hayre',
 'Kiaan Anand',
 'Shayak Saran',
 'Amani Tailor',
 'Purab Karpe',
 'Aaryahi Ahluwalia',
 'Adira Ghosh',
 'Umang Hayre',
 'Drishya Vaidya',
 'Rania Deshpande',
 'Anya Kohli',
 'Ryan Bumb',
 'Arhaan Ghosh',
 'Eva Raval',
 'Lakshay Bobal',
 'Veer Mander',
 'Mahika Batra',
 'Neelofar Sibal',
 'Amira Venkataraman',
 'Nirvi Ratti',
 'Biju Soman',
 'Amani Wali',
 'Yakshit Goel',
 'Zoya Garg',
 'Stuvan Ravi',
 'Nirvi Chakrabarti',
 'Elakshi Doshi',
 'Mahika Bahl',
 'Yakshit Chander',
 'Samarth Sangha',
 'Mishti Das',
 'Saksham Bahl',
 'Manikya Bumb',
 'Rhea Boase',
 'Aarna Wable',
 'Ela Kumer',
 'Vedika Tiwari',
 'Lakshay Ghose',
 'Armaan Comar',
 'Purab Sarin',
 'Mannat Ganesan',
 'Zara Dixit',
 'Devansh Sharaf',
 'Nayantara Dhaliwal',
 'Vivaan Ravi',
 'Anay Lad',
 'Suhana Chaudhry',
 'Manikya Ghose',
 'Taran Deep',
 'Anahita Kale',
 'Inaaya  Boase',
 'Badal Dasgupta',
 'Miraya Soni',
 'Sumer Sane',
 'Fateh Kapadia',
 'Madhav Dara',
 'Ranbir Agate',
 'Anaya Chaudhuri',
 'Dishani Banerjee',
 'Riya Karnik',
 'Zeeshan Acharya',
 'Taran Sami',
 'Darshit Sani',
 'Ivan Mahajan',
 'Zaina Chakraborty',
 'Mannat Arora',
 'Gatik Sethi',
 'Reyansh Divan',
 'Kiaan Bhatti',
 'Miraan Bera',
 'Priyansh Verma',
 'Arhaan Mangal',
 'Miraan Warrior',
 'Anya Gupta',
 'Divyansh Shukla',
 'Ishaan Verma',
 'Bhavin Ben',
 'Ryan Choudhry',
 'Oorja Bhatti',
 'Hazel Lad',
 'Riya Kala',
 'Biju Dugar',
 'Arhaan Kar',
 'Shamik Kanda',
 'Riya Rajagopal',
 'Vivaan Kaul',
 'Ritvik Bandi',
 'Shlok Saraf',
 'Jiya Vora',
 'Yuvraj  Maharaj',
 'Farhan Malhotra',
 'Priyansh Baria',
 'Miraya Dutt',
 'Tanya Singhal',
 'Shamik Batra',
 'Jiya Sarkar',
 'Parinaaz Dyal',
 'Drishya Ray',
 'Elakshi Dasgupta',
 'Keya Toor',
 'Anya Shanker',
 'Kabir Krishna',
 'Yuvraj  Dash',
 'Adah Keer',
 'Divij Basu',
 'Shanaya Baral',
 'Amani Sant',
 'Vaibhav Dugal',
 'Kaira Arya',
 'Manikya Bhat',
 'Trisha Saha',
 'Kabir Acharya',
 'Samaira Chandra',
 'Parinaaz Date',
 'Taimur Sarna',
 'Sara Bala',
 'Adah Deshpande',
 'Neelofar Wagle',
 'Miraan Upadhyay',
 'Ayesha Chad',
 'Nitara Kaur',
 'Samiha Tak',
 'Raunak Ramachandran',
 'Purab Jaggi',
 'Neysa Bains',
 'Anaya Dora',
 'Bhamini Solanki',
 'Eshani Ravi',
 'Seher Kakar',
 'Divij Rout',
 'Veer Dalal',
 'Divit Aurora',
 'Ayesha Aurora',
 'Misha Trivedi',
 'Aaina Hayre',
 'Piya Shan',
 'Parinaaz Jaggi',
 'Nirvaan Dey',
 'Sumer Sharma',
 'Vedika Mammen',
 'Kaira Rattan',
 'Aarav Bava',
 'Mahika Vohra',
 'Prisha Warrior',
 'Prerak Virk',
 'Samarth Kulkarni',
 'Jivin Loyal',
 'Riya Ghose',
 'Fateh Bir',
 'Emir Bala',
 'Misha Srinivasan',
 'Ela Chaudhuri',
 'Charvi Kari',
 'Anvi Tripathi',
 'Shlok Tella',
 'Misha Mall',
 'Shalv Johal',
 'Zain Subramaniam',
 'Samarth Aggarwal',
 'Shaan Chokshi',
 'Yakshit Kapadia',
 'Ojas Dhillon',
 'Uthkarsh Wali',
 'Mahika Batta',
 'Ritvik Rana',
 'Yuvaan Tandon',
 'Vedika Virk',
 'Nishith Badal',
 'Damini Zacharia',
 'Indrans Raj',
 'Parinaaz Dey',
 'Piya Sengupta',
 'Pari Kadakia',
 'Miraan Saha',
 'Anvi Rao',
 'Ayesha Andra',
 'Nishith Seth',
 'Lavanya Dhar',
 'Aaina Kashyap',
 'Tara Comar',
 'Sahil Agarwal',
 'Nirvi Dhawan',
 'Sumer Bhavsar',
 'Jayan Dasgupta',
 'Ela Hora',
 'Aaryahi Dutt',
 'Charvi Bhakta',
 'Farhan Bhardwaj',
 'Divyansh Wagle',
 'Baiju Sanghvi',
 'Khushi Kala',
 'Advik Bansal',
 'Seher Choudhury',
 'Bhamini Saraf',
 'Veer Kapadia',
 'Hansh Krishnan',
 'Ivana Agrawal',
 'Aaina Subramaniam',
 'Tarini Lal',
 'Kabir Sahota',
 'Reyansh Kakar',
 'Rohan Balakrishnan',
 'Kanav Ranganathan',
 'Trisha Date',
 'Divit Kumer',
 'Romil Sathe',
 'Siya Agate',
 'Dhanuk Maharaj',
 'Neelofar Swamy',
 'Arhaan Ravi',
 'Bhavin Bansal',
 'Priyansh Shah',
 'Dhanush Din',
 'Jhanvi Mahajan',
 'Ela Jain',
 'Taimur Varty',
 'Baiju Sagar',
 'Nitara Sha',
 'Hrishita Basak',
 'Vihaan Edwin',
 'Neelofar Goel',
 'Oorja Bahl',
 'Faiyaz Singh',
 'Baiju Chowdhury',
 'Yasmin Bhardwaj',
 'Shalv Dhawan',
 'Bhamini Ramesh',
 'Mamooty Kar',
 'Raunak Sekhon',
 'Samarth Tandon',
 'Mannat Kibe',
 'Arhaan Kata',
 'Kanav Garg',
 'Aaryahi Date',
 'Vivaan Seth',
 'Trisha Sule',
 'Khushi Sheth',
 'Renee Bhattacharyya',
 'Ojas Sarraf',
 'Myra Gandhi',
 'Oorja Balan',
 'Keya Chawla',
 'Ayesha Rao',
 'Divyansh Sama',
 'Sara Dora',
 'Sana Mander',
 'Farhan Kumer',
 'Nirvi Sodhi',
 'Nitya Sachdeva',
 'Adira Gola',
 'Nayantara Johal',
 'Sahil Lad',
 'Vidur Guha',
 'Samarth Konda',
 'Mamooty Chaudhuri',
 'Vritika Dubey',
 'Kiara Handa',
 'Vardaniya Som',
 'Jayant Master',
 'Khushi Goda',
 'Sara Babu',
 'Anay Dutta',
 'Mamooty Subramaniam',
 'Uthkarsh Lalla',
 'Advik Guha',
 'Seher Shukla',
 'Rasha Sawhney',
 'Kanav Kapadia',
 'Khushi Sem',
 'Jivika Jani',
 'Bhamini Balay',
 'Zoya Ranganathan',
 'Mehul Mangal',
 'Renee Sundaram',
 'Shaan Rajagopalan',
 'Jhanvi Chadha',
 'Pranay Rama',
 'Vihaan Vala',
 'Alisha Tara',
 'Dhruv Hari',
 'Shanaya Gole',
 'Siya Bir',
 'Nitara Wali',
 'Ivan Sama',
 'Tiya Chahal',
 'Rati Sarraf',
 'Ela Devi',
 'Stuvan Reddy',
 'Urvi Jha',
 'Jivin Sankaran',
 'Myra Setty',
 'Divij Dhar',
 'Tarini Dara',
 'Aradhya Varghese',
 'Zaina Khare',
 'Anahi Chanda',
 'Ryan Handa',
 'Urvi Sachdeva',
 'Vedika Datta',
 'Shlok Ray',
 'Sahil Ganesan',
 'Anahi Malhotra',
 'Kiara Raval',
 'Yashvi Khosla',
 'Anya Upadhyay',
 'Fateh Raval',
 'Alia Shukla',
 'Priyansh Desai',
 'Alisha Raju',
 'Devansh Bobal',
 'Ojas Datta',
 'Aarna Chaudhari',
 'Nitya Choudhry',
 'Anahita Kalla',
 'Indranil Bains',
 'Saksham Sampath',
 'Aarna Gala',
 'Indrajit Borra',
 'Rati Gaba',
 'Damini Wadhwa',
 'Elakshi Ahluwalia',
 'Lavanya Mammen',
 'Vihaan Sood',
 'Amani Kumer',
 'Dhruv Kaul',
 'Rohan Subramanian',
 'Faiyaz Warrior',
 'Yashvi Singh',
 'Parinaaz Lalla',
 'Samiha Lanka',
 'Vritika Shroff',
 'Madhup Sehgal',
 'Anahita Seshadri',
 'Anika Wali',
 'Kiaan Brar',
 'Ishita Ratti',
 'Kashvi Joshi',
 'Pari Raja',
 'Nayantara Chatterjee',
 'Vidur Sood',
 'Sahil Subramaniam',
 'Vidur Lalla',
 'Mehul Sawhney',
 'Navya Varma',
 'Vihaan Behl',
 'Saksham Doctor',
 'Romil Kapadia',
 'Inaaya  Sandhu',
 'Samar Sachdeva',
 'Zeeshan Taneja',
 'Divit Kohli',
 'Charvi Mandal',
 'Nirvaan Bumb',
 'Ela Krishnamurthy',
 'Alisha Kakar',
 'Eva Mani',
 'Mehul Wali',
 'Onkar Sani',
 'Shamik Taneja',
 'Jivika Singh',
 'Jayant Thakur',
 'Shaan Savant',
 'Mannat Wason',
 'Nitya Ahuja',
 'Bhamini Chandra',
 'Aayush Baral',
 'Ritvik Krish',
 'Lakshit Mani',
 'Hazel Buch',
 'Urvi Garg',
 'Mohanlal Bakshi',
 'Himmat Divan',
 'Heer Wadhwa',
 'Divij Kulkarni',
 'Neelofar Chaudry',
 'Vritika Deol',
 'Himmat Dar',
 'Prerak Anne',
 'Aarush Ramaswamy',
 'Anahi Sarin',
 'Ahana  Kamdar',
 'Heer Kant',
 'Vedika Bera',
 'Vihaan Dara',
 'Kabir Grover',
 'Drishya Mani',
 'Riya Madan',
 'Fateh Gala',
 'Ishita Bir',
 'Nehmat Borra',
 'Ranbir Wable',
 'Manjari Gill',
 'Pihu Gera',
 'Aradhya Ramesh',
 'Farhan Wagle',
 'Vaibhav Tripathi',
 'Jivin Kapadia',
 'Jiya Kothari',
 'Prisha Ramanathan',
 'Rhea Gole',
 'Urvi Goel',
 'Nakul Hora',
 'Anika Verma',
 'Yasmin Subramaniam',
 'Rati Baral',
 'Rania Mani',
 'Vidur Sarkar',
 'Zeeshan Bhagat',
 'Khushi Wadhwa',
 'Vihaan Barad',
 'Zain Kunda',
 'Jayant Doctor',
 'Kiaan Sarma',
 'Samaira Thakur',
 'Baiju Kari',
 'Baiju Dey',
 'Anvi Salvi',
 'Vanya Ramaswamy',
 'Advika Krish',
 'Aarav Deshpande',
 'Hrishita Kar',
 'Armaan Viswanathan',
 'Indrajit Hans',
 'Oorja Behl',
 'Heer Anand',
 'Stuvan Mangat',
 'Devansh Ghose',
 'Urvi Sem',
 'Yasmin Kanda',
 'Badal Acharya',
 'Jhanvi Dyal',
 'Rati Chokshi',
 'Gokul Chada',
 'Pihu Ganesh',
 'Jhanvi Date',
 'Nirvaan Gara',
 'Shaan Gour',
 'Sumer Dara',
 'Heer Halder',
 'Jivika Shukla',
 'Zara Chatterjee',
 'Ela Amble',
 'Riya Kibe',
 'Divyansh Mangat',
 'Anaya Ramanathan',
 'Abram Kothari',
 'Yashvi Khanna',
 'Hrishita Bhattacharyya',
 'Kimaya Borra',
 'Misha Dey',
 'Siya Barman',
 'Onkar Ramaswamy',
 'Ishita Sur',
 'Aarav Saini',
 'Vihaan Mann',
 'Aarna Kothari',
 'Shalv Dewan',
 'Amani Dada',
 'Mamooty Ravi',
 'Vaibhav Brar',
 'Onkar Issac',
 'Lavanya Dhawan',
 'Ahana  Walla',
 'Zoya Kulkarni',
 'Manikya Ravi',
 'Rasha Master',
 'Miraya Keer',
 'Mamooty Mand',
 'Indrajit Doctor',
 'Aradhya Batta',
 'Madhup Som',
 'Amira Arora',
 'Gokul Mander',
 'Nirvaan Sagar',
 'Mohanlal Madan',
 'Kabir Gupta',
 'Raunak Hari',
 'Kabir Loyal',
 'Yuvaan Comar',
 'Azad Mander',
 'Yuvaan Bains',
 'Anahi Tak',
 'Saanvi Jhaveri',
 'Seher Ramaswamy',
 'Lavanya Sandal',
 'Nirvaan Sridhar',
 'Yasmin Luthra',
 'Vardaniya Keer',
 'Anahita Sant',
 'Hunar Upadhyay',
 'Ehsaan Behl',
 'Mohanlal Dey',
 'Samar Goswami',
 'Rhea Dhar',
 'Diya Buch',
 'Neelofar Kalita',
 'Aradhya Jain',
 'Ivan Seshadri',
 'Gatik Bahl',
 'Aayush Kadakia',
 'Hunar Anne',
 'Aarna Varughese',
 'Arnav Sood',
 'Kaira Dewan',
 'Mohanlal Vasa',
 'Jayant Goyal',
 'Charvi Bhatt',
 'Anahita Jani',
 'Hrishita Sahni',
 'Trisha Shah',
 'Anvi Gopal',
 'Jiya Mand',
 'Ira Joshi',
 'Kashvi Sibal',
 'Divit Bhavsar',
 'Tanya Chaudhuri',
 'Nirvi Ratta',
 'Damini Ramachandran',
 'Aradhya Doctor',
 'Nayantara Kothari',
 'Neelofar Amble',
 'Alisha Bora',
 'Alia Mall',
 'Purab Sha',
 'Jivika Bhasin',
 'Parinaaz Vaidya',
 'Vanya Sachar',
 'Purab Mangal',
 'Badal Sangha',
 'Nirvaan Lad',
 'Myra Seshadri',
 'Dharmajan Subramaniam',
 'Misha Mannan',
 'Jiya Rau',
 'Amani Saraf',
 'Khushi Baral',
 'Aaina Talwar',
 'Aarav Agarwal',
 'Taimur Malhotra',
 'Parinaaz Bassi',
 'Biju Handa',
 'Miraan Agrawal',
 'Saksham Dewan',
 'Taran Gala',
 'Anika Kuruvilla',
 'Misha Bhasin',
 'Aaryahi Sani',
 'Kismat Ganguly',
 'Alisha Jha',
 'Raghav Bahri',
 'Shanaya Ganesan',
 'Manikya Venkatesh',
 'Mannat Kumar',
 'Jayan Bail',
 'Saanvi Tripathi',
 'Priyansh Wadhwa',
 'Tiya Saini',
 'Vanya Deol',
 'Divyansh Saini',
 'Kartik Vasa',
 'Nirvi Dey',
 'Prisha Ganesan',
 'Mehul Venkatesh',
 'Dhanuk Swaminathan',
 'Saksham Bahri',
 'Parinaaz Sen',
 'Ayesha Banik',
 'Fateh Toor',
 'Advika Choudhury',
 'Prisha Samra',
 'Tiya Dugar',
 'Nitara Raman',
 'Reyansh Kashyap',
 'Armaan Tella',
 'Ira Bobal',
 'Mannat Sami',
 'Nitya Kari',
 'Urvi Chada',
 'Advik Rattan',
 'Rohan Singhal',
 'Shayak Butala',
 'Ritvik Dutta',
 'Faiyaz Chaudry',
 'Nirvaan Tata',
 'Elakshi Joshi',
 'Inaaya  Sur',
 'Vardaniya Wagle',
 'Baiju Sur',
 'Vidur Bava',
 'Suhana Chakrabarti',
 'Aarush Dutt',
 'Vardaniya Bedi',
 'Krish Manne',
 'Faiyaz Deshpande',
 'Raunak Bhavsar',
 'Bhavin Arora',
 'Nakul Chawla',
 'Raghav Saran',
 'Ranbir Bahri',
 'Heer Salvi',
 'Rhea Doctor',
 'Shlok Saha',
 'Drishya Sarna',
 'Ojas Borra',
 'Sara Walla',
 'Anahita Bhalla',
 'Mamooty Shukla',
 'Renee Dave',
 'Vanya Lad',
 'Zaina Brahmbhatt',
 'Krish Ahluwalia',
 'Zara Sem',
 'Faiyaz Kari',
 'Kiara Walla',
 'Ranbir Balan',
 'Aarna Sule',
 'Stuvan Taneja',
 'Kaira Loyal',
 'Rohan Deol',
 'Yasmin Chanda',
 'Vanya Barman',
 'Hiran Buch',
 'Sumer Sachdev',
 'Vivaan Balay',
 'Alia Butala',
 'Anika Ahluwalia',
 'Riya Luthra',
 'Aniruddh Hayer',
 'Pihu Chauhan',
 'Divij Sani',
 'Nirvi Vohra',
 'Parinaaz Chada',
 'Divyansh Saraf',
 'Jiya Taneja',
 'Yuvraj  Dutt',
 'Raunak Thaman',
 'Shanaya Dyal',
 'Shalv Badal',
 'Kavya Sathe',
 'Nayantara Krish',
 'Jivin Sahota',
 'Kavya Cherian',
 'Rohan Borra',
 'Ishita Kibe',
 'Emir Dora',
 'Tanya Ravel',
 'Charvi Dar',
 'Anvi Sundaram',
 'Khushi Gandhi',
 'Anay Vora',
 'Abram Tailor',
 'Kartik Sarraf',
 'Amira Bali',
 'Armaan Reddy',
 ...]

**Build a frequency count of one categorical field across all 8 records (like the word-frequency example from lecture), using a plain dictionary and .get().**

In [ ]:
from collections import Counter

all_cardholder_names = [record_dict['Cardholder Name'] for record_dict in named_red]

name_frequencies = Counter(all_cardholder_names)

name_frequencies.most_common(3)

[('Saanvi Dey', 3), ('Uthkarsh Soman', 3), ('Mamooty Chaudhuri', 3)]

In [ ]:
cols

('Transaction Date and Time',
 'Transaction Amount',
 'Cardholder Name',
 'Card Number (Hashed or Encrypted)',
 'Merchant Name',
 'Merchant Category Code (MCC)',
 'Transaction Location (City or ZIP Code)',
 'Transaction Currency',
 'Card Type',
 'Card Expiration Date',
 'CVV Code (Hashed or Encrypted)',
 'Transaction Response Code',
 'Transaction ID',
 'Fraud Flag or Label',
 'Previous Transactions',
 'Transaction Source',
 'IP Address',
 'Device Information',
 'User Account Information',
 'Transaction Notes')

# **Task 4 — Filter with a boolean mask**

In [ ]:
mask=[]
for i in named_red:
  if (i['Transaction Amount']>3800):
     mask.append(i)
len(mask)
mask

[{'Transaction Date and Time': '2023-03-18 01:05:36',
  'Transaction Amount': 3939.01,
  'Cardholder Name': 'Riya Bobal',
  'Card Number (Hashed or Encrypted)': '4737a6384aa1c3c31f7768b86633d6a8401dd6ab4a8ff1f3c876a82830a98e57',
  'Merchant Name': 'Badal PLC',
  'Merchant Category Code (MCC)': 9297,
  'Transaction Location (City or ZIP Code)': 'Nangloi Jat',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '11/29',
  'CVV Code (Hashed or Encrypted)': 'eb3be230bbd2844b1f5d8f2e4fab9ffba8ab22cfeeb69c4c1361993ba4f377b9',
  'Transaction Response Code': 5,
  'Transaction ID': 'f09cecd6-0d74-4551-8089-a31d64e6b9c5',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'In-Person',
  'IP Address': '17.190.112.46',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Unde beatae perspiciatis sapiente. Voluptates magnam debitis facere officiis assumenda.\nDolorum nisi consequatur delectus sint dolor dolorum. Quae ullam nihil ullam.'},
 {'Transaction Date and Time': '2022-09-10 05:59:18',
  'Transaction Amount': 4514.53,
  'Cardholder Name': 'Ivan Loyal',
  'Card Number (Hashed or Encrypted)': '8d7967ba4a7d372708eca312d518026dd2d83d42e5f0be0e60ea4d033ab62236',
  'Merchant Name': 'Sant, Chawla and Wali',
  'Merchant Category Code (MCC)': 8521,
  'Transaction Location (City or ZIP Code)': 'Aizawl',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '08/29',
  'CVV Code (Hashed or Encrypted)': 'e6f095e985e6762f1538b47ff1abda58dbe8ce088b16d8a5744fc179e9a2fc16',
  'Transaction Response Code': 0,
  'Transaction ID': 'df575129-3416-4c59-b282-d57267515ce1',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'In-Person',
  'IP Address': '39.33.247.78',
  'Device Information': 'Tablet',
  'User Account Information': 'ydey',
  'Transaction Notes': 'Architecto natus neque fuga. Voluptate dolor illo laboriosam quo harum.\nId error ex iusto dolores hic fuga autem. Adipisci ea quo.\nAspernatur recusandae mollitia ratione doloremque inventore.'},
 {'Transaction Date and Time': '2021-10-10 00:09:01',
  'Transaction Amount': 4572.85,
  'Cardholder Name': 'Kiara Desai',
  'Card Number (Hashed or Encrypted)': '26a3916ef3ef68e9896cc72ca5b4c3ed805ff55b2ed36edccdf2366d11fb0b13',
  'Merchant Name': 'Anand Group',
  'Merchant Category Code (MCC)': 3001,
  'Transaction Location (City or ZIP Code)': 'Vijayanagaram',
  'Transaction Currency': 'EUR',
  'Card Type': 'MasterCard',
  'Card Expiration Date': '12/24',
  'CVV Code (Hashed or Encrypted)': 'bd94717d91260895035088525e817ea10375454f03aa3bd8b28b355a4cee22c5',
  'Transaction Response Code': 5,
  'Transaction ID': '8fa4605b-dcad-4d92-80b3-0a64172cbfbd',
  'Fraud Flag or Label': 0,
  'Previous Transactions': nan,
  'Transaction Source': 'In-Person',
  'IP Address': '162.26.105.72',
  'Device Information': 'Desktop',
  'User Account Information': 'siya72',
  'Transaction Notes': 'Perspiciatis commodi corrupti. Iusto deleniti sed. Veniam numquam quod rem numquam ea.'},
 {'Transaction Date and Time': '2022-05-03 17:20:53',
  'Transaction Amount': 4172.21,
  'Cardholder Name': 'Tanya Khalsa',
  'Card Number (Hashed or Encrypted)': '3fe204cb8cf91a36f31cb8009e3ec5749d147007babf9ab54f825e577cf0e4d3',
  'Merchant Name': 'Randhawa, Khanna and Kamdar',
  'Merchant Category Code (MCC)': 2162,
  'Transaction Location (City or ZIP Code)': 'Bhagalpur',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '08/30',
  'CVV Code (Hashed or Encrypted)': 'd86580a57f7bf542e85202283cb845953c9d28f80a8e651db08b2fc0b2d6a731',
  'Transaction Response Code': 5,
  'Transaction ID': 'a836d1e0-9e0f-490a-b8aa-f8c67da63b02',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '1',
  'Transaction Source': 'In-Person',
  'IP Address': '151.74.51.49',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Ducimus optio nulla ad cum deserunt eum. Aliquam aperiam facere ipsam.\nDucimus provident perspiciatis esse quae corporis. Ducimus omnis quidem atque voluptatum cupiditate veniam.'},
 {'Transaction Date and Time': '2022-05-17 17:20:40',
  'Transaction Amount': 4014.63,
  'Cardholder Name': 'Khushi Bhat',
  'Card Number (Hashed or Encrypted)': '0d1bc479a91ac7f4201701bd6479c19fe1b8d0cbbc82e2b213dc03a3a3316262',
  'Merchant Name': 'Butala, Saraf and Banik',
  'Merchant Category Code (MCC)': 3962,
  'Transaction Location (City or ZIP Code)': 'Cuttack',
  'Transaction Currency': 'INR',
  'Card Type': 'MasterCard',
  'Card Expiration Date': '03/26',
  'CVV Code (Hashed or Encrypted)': '188c1fdca79d927f6e812133173fc41d3a4e57074de521020274caa9bb29af7d',
  'Transaction Response Code': 12,
  'Transaction ID': '7aff8237-12db-4a5b-8002-2ad12f6eee9e',
  'Fraud Flag or Label': 0,
  'Previous Transactions': '2',
  'Transaction Source': 'In-Person',
  'IP Address': '186.38.145.46',
  'Device Information': 'Tablet',
  'User Account Information': 'etak',
  'Transaction Notes': 'Voluptatum assumenda aliquid iure sit. At dicta ratione. Cumque esse ipsum architecto.'},
 {'Transaction Date and Time': '2021-09-12 22:28:26',
  'Transaction Amount': 4666.18,
  'Cardholder Name': 'Biju Sekhon',
  'Card Number (Hashed or Encrypted)': '338b9395844421a2096fda821637077e681657751ca7f6d4b5422b269fa46317',
  'Merchant Name': 'Kothari, Dhillon and Sandhu',
  'Merchant Category Code (MCC)': 4830,
  'Transaction Location (City or ZIP Code)': 'Dharmavaram',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '01/30',
  'CVV Code (Hashed or Encrypted)': '03a3d955b8799a90f1ff5a39479fde8e618f8ca3282d5b187186f2cf361abd32',
  'Transaction Response Code': 12,
  'Transaction ID': 'd6641824-cc25-4492-b60a-cc4c66d9cbd0',
  'Fraud Flag or Label': 0,
  'Previous Transactions': '1',
  'Transaction Source': 'Online',
  'IP Address': '172.233.211.200',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'In facilis neque impedit pariatur. Non eaque facilis at corporis reprehenderit ut.'},
 {'Transaction Date and Time': '2020-11-08 09:53:02',
  'Transaction Amount': 4326.69,
  'Cardholder Name': 'Kiara Yadav',
  'Card Number (Hashed or Encrypted)': '41bdc3047bfb6a3f1545aa9318004826eb2becc4d342c9ab2797fd7817fa4369',
  'Merchant Name': 'Venkataraman-Dhar',
  'Merchant Category Code (MCC)': 1655,
  'Transaction Location (City or ZIP Code)': 'Erode',
  'Transaction Currency': 'USD',
  'Card Type': 'MasterCard',
  'Card Expiration Date': '07/29',
  'CVV Code (Hashed or Encrypted)': '4c15f47afe7f817fd559e12ddbc276f4930c5822f2049088d6f6605bec7cea56',
  'Transaction Response Code': 0,
  'Transaction ID': '56ed77d7-6f6c-466f-9f3b-744acf19e3fc',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'Online',
  'IP Address': '204.234.68.60',
  'Device Information': 'Desktop',
  'User Account Information': 'nayantara89',
  'Transaction Notes': 'Odio iste in ut velit aliquam inventore. Autem ratione quasi temporibus delectus laborum. Ipsam tempora similique pariatur eum rerum accusamus. Commodi voluptates accusantium laudantium nesciunt.'},
 {'Transaction Date and Time': '2020-02-21 04:44:43',
  'Transaction Amount': 4525.17,
  'Cardholder Name': 'Kashvi Kothari',
  'Card Number (Hashed or Encrypted)': '56370969fe7251f3a2bef5b6ccbee83a7864d3ce8dde3f28a78716af8c6f6e51',
  'Merchant Name': 'Jha-Maharaj',
  'Merchant Category Code (MCC)': 9106,
  'Transaction Location (City or ZIP Code)': 'Madanapalle',
  'Transaction Currency': 'USD',
  'Card Type': 'American Express',
  'Card Expiration Date': '08/30',
  'CVV Code (Hashed or Encrypted)': '6ea2fdb3399f4d2e806beb01e9a3371bd622bed6a409acf3151818d738c370ec',
  'Transaction Response Code': 0,
  'Transaction ID': '96e56db9-59b8-433b-a5d2-07927b03e490',
  'Fraud Flag or Label': 0,
  'Previous Transactions': '2',
  'Transaction Source': 'Online',
  'IP Address': '115.64.177.18',
  'Device Information': 'Desktop',
  'User Account Information': nan,
  'Transaction Notes': 'Molestiae officiis rem. Aspernatur nulla quasi occaecati placeat excepturi.\nVitae natus occaecati delectus dolor sapiente. Praesentium numquam qui veniam officia corrupti totam.'},
 {'Transaction Date and Time': '2020-04-19 16:54:35',
  'Transaction Amount': 4469.12,
  'Cardholder Name': 'Divij Kaur',
  'Card Number (Hashed or Encrypted)': '24524e12778f12a4dd470c807cecdc1b20ffecb62f67b0281d1a026029122765',
  'Merchant Name': 'Baral-Zachariah',
  'Merchant Category Code (MCC)': 2539,
  'Transaction Location (City or ZIP Code)': 'Indore',
  'Transaction Currency': 'INR',
  'Card Type': 'MasterCard',
  'Card Expiration Date': '06/29',
  'CVV Code (Hashed or Encrypted)': '4771bef2c04a34b548b77ea7581cf821152d9dea9c2c85151a07856fe3639314',
  'Transaction Response Code': 5,
  'Transaction ID': '1a243f63-b3ca-416f-a73c-c2844450d2ff',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'Online',
  'IP Address': '178.107.59.132',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Corporis nulla eius distinctio delectus. Iusto voluptas tempora corrupti rem tempora perferendis rem. Reprehenderit corporis ratione at inventore amet maiores.'},
 {'Transaction Date and Time': '2022-12-27 09:35:58',
  'Transaction Amount': 4432.28,
  'Cardholder Name': 'Zain Chopra',
  'Card Number (Hashed or Encrypted)': '6f6dfeace5d2499b7b59abea66cd388a6a78f28534c23d067f2fb79046965aeb',
  'Merchant Name': 'Divan, Cheema and Dugar',
  'Merchant Category Code (MCC)': 1880,
  'Transaction Location (City or ZIP Code)': 'Jehanabad',
  'Transaction Currency': 'INR',
  'Card Type': 'Visa',
  'Card Expiration Date': '10/24',
  'CVV Code (Hashed or Encrypted)': '9e6a72557ada15d02001f024f43f06edc4a31437e0e1bb3eeac36ca2d0c4fda7',
  'Transaction Response Code': 0,
  'Transaction ID': 'f8cb87ee-cc99-41b9-8369-0ca905918a50',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'In-Person',
  'IP Address': '135.165.132.148',
  'Device Information': 'Desktop',
  'User Account Information': nan,
  'Transaction Notes': 'Illum debitis nisi laborum. Quo id maxime porro nobis. Eligendi neque vero odio inventore doloribus.'},
 {'Transaction Date and Time': '2020-06-01 21:41:24',
  'Transaction Amount': 4801.36,
  'Cardholder Name': 'Vihaan Randhawa',
  'Card Number (Hashed or Encrypted)': '74393ce588bf6651ca56fe761f4fa076814dfd8737ae028e8900125a9b1b6c4e',
  'Merchant Name': 'Soman LLC',
  'Merchant Category Code (MCC)': 2558,
  'Transaction Location (City or ZIP Code)': 'Jalna',
  'Transaction Currency': 'EUR',
  'Card Type': 'Visa',
  'Card Expiration Date': '10/31',
  'CVV Code (Hashed or Encrypted)': '084917af148384c1e8396addcec2fca2a9f2c3918cad9676e12cdaad7dc7dfb2',
  'Transaction Response Code': 5,
  'Transaction ID': '1818c356-5b54-40a9-8e1e-3cad815f1567',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'Online',
  'IP Address': '195.242.42.170',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Odit sunt neque sapiente repellat nesciunt. Molestias veritatis officiis deserunt modi.\nPossimus repellendus deserunt nisi culpa quae. Deleniti labore veritatis pariatur asperiores alias commodi.'},
 {'Transaction Date and Time': '2023-03-09 19:32:57',
  'Transaction Amount': 4058.43,
  'Cardholder Name': 'Aarna Wadhwa',
  'Card Number (Hashed or Encrypted)': 'ff63b578121ed224a1eee0f8c9b5691d78fe0673b77f70cda00d889d6db09aee',
  'Merchant Name': 'Dara Inc',
  'Merchant Category Code (MCC)': 7695,
  'Transaction Location (City or ZIP Code)': 'Bareilly',
  'Transaction Currency': 'USD',
  'Card Type': 'American Express',
  'Card Expiration Date': '03/29',
  'CVV Code (Hashed or Encrypted)': '87acb1e183a2b0f74c3b2008b8ef6975a95269bc490a8886f317fa4bd714b085',
  'Transaction Response Code': 12,
  'Transaction ID': '1b6a4055-6327-4af8-960c-9307a4f31f58',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'In-Person',
  'IP Address': '18.64.162.173',
  'Device Information': 'Desktop',
  'User Account Information': 'iyerpranay',
  'Transaction Notes': 'Impedit id temporibus ex modi fugit quibusdam. Esse quisquam voluptatem perferendis excepturi cum impedit sint. Tempora officia officia. Ipsa pariatur debitis doloribus.'},
 {'Transaction Date and Time': '2020-02-15 15:22:13',
  'Transaction Amount': 4993.49,
  'Cardholder Name': 'Ranbir Uppal',
  'Card Number (Hashed or Encrypted)': '08e03cf4378eb4ef23547fd4e59243188d3d0966c5d31e2cffa37ec80d7243c3',
  'Merchant Name': 'Raja, Bhat and Chander',
  'Merchant Category Code (MCC)': 5307,
  'Transaction Location (City or ZIP Code)': 'Barasat',
  'Transaction Currency': 'EUR',
  'Card Type': 'Visa',
  'Card Expiration Date': '05/26',
  'CVV Code (Hashed or Encrypted)': 'b967fb22d506bda1b4d8a878f46c85862f5d71bb7669ecc6b0fe65f5ad19f844',
  'Transaction Response Code': 12,
  'Transaction ID': 'd97d1232-484b-4dda-b52a-f56a1e4c1649',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'Online',
  'IP Address': '176.60.44.187',
  'Device Information': 'Mobile',
  'User Account Information': 'yasmin25',
  'Transaction Notes': 'Optio soluta fuga repellat. Beatae ipsam et nesciunt ratione unde quo.\nTempora fugit nam enim quibusdam sapiente. Porro eligendi repudiandae.\nQuod soluta officia distinctio.'},
 {'Transaction Date and Time': '2022-04-16 00:52:05',
  'Transaction Amount': 4102.82,
  'Cardholder Name': 'Armaan Dar',
  'Card Number (Hashed or Encrypted)': 'ada39ccd00d99283e5a55c2ad3a796eb26638c0faa8fc0f36ecb698b224cbf6f',
  'Merchant Name': 'Kumer, Roy and Dutt',
  'Merchant Category Code (MCC)': 8007,
  'Transaction Location (City or ZIP Code)': 'Chapra',
  'Transaction Currency': 'USD',
  'Card Type': 'American Express',
  'Card Expiration Date': '08/26',
  'CVV Code (Hashed or Encrypted)': '7f3ee9fe1fbf452b0c242614e1cad18b6dce034e5bc80763dff6332e872ad2ff',
  'Transaction Response Code': 5,
  'Transaction ID': 'a1689d2b-6353-44b6-9a66-45f61f460a7d',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'In-Person',
  'IP Address': '211.94.41.11',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Quo et ipsam quam sed. Laborum repudiandae nobis quod enim pariatur aut. Voluptatem recusandae adipisci officiis architecto.'},
 {'Transaction Date and Time': '2023-06-25 11:07:54',
  'Transaction Amount': 4875.85,
  'Cardholder Name': 'Amira Uppal',
  'Card Number (Hashed or Encrypted)': '5d376d0ba49d1eb07b6665fba2db2f40624bf4d092c7b1c5ec10416b207640ca',
  'Merchant Name': 'Dugar, Kari and Dar',
  'Merchant Category Code (MCC)': 5347,
  'Transaction Location (City or ZIP Code)': 'Karaikudi',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '04/32',
  'CVV Code (Hashed or Encrypted)': '8920a14a7f6469b955b114111564cb9736440238d220fc9fd525efdb9a056d3e',
  'Transaction Response Code': 12,
  'Transaction ID': '61f89f2e-7bf2-46c7-a0f3-d88aaf501e2f',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'Online',
  'IP Address': '217.201.60.20',
  'Device Information': 'Tablet',
  'User Account Information': nan,
  'Transaction Notes': 'Accusamus delectus fugiat aperiam voluptates tenetur. Reiciendis deserunt repellendus error maxime. Sit nisi repellat doloremque sapiente voluptates.'},
 {'Transaction Date and Time': '2021-06-05 16:32:37',
  'Transaction Amount': 4788.09,
  'Cardholder Name': 'Zeeshan Lalla',
  'Card Number (Hashed or Encrypted)': '63fa974ab1e5c7b534274f7260746648a65473d6431f08fea400cfde21da6bb2',
  'Merchant Name': 'Chad Inc',
  'Merchant Category Code (MCC)': 6641,
  'Transaction Location (City or ZIP Code)': 'Ranchi',
  'Transaction Currency': 'USD',
  'Card Type': 'Visa',
  'Card Expiration Date': '10/29',
  'CVV Code (Hashed or Encrypted)': '5c17cac5569c1ab72a3f009c7608dfc49299ad8f447e4724030ea416383b04fd',
  'Transaction Response Code': 5,
  'Transaction ID': '2ecdd23f-b0f7-4de9-8de6-79916bbcc709',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '2',
  'Transaction Source': 'In-Person',
  'IP Address': '181.172.135.146',
  'Device Information': 'Tablet',
  'User Account Information': 'samarswaminathan',
  'Transaction Notes': 'Explicabo autem porro officiis voluptate. Magnam nobis aspernatur dolorum perspiciatis distinctio.'},
 {'Transaction Date and Time': '2021-10-22 17:04:31',
  'Transaction Amount': 4165.48,
  'Cardholder Name': 'Samar Borah',
  'Card Number (Hashed or Encrypted)': '0d2618414c8083d780db4ab48b71796ef94ed67354329741005e8feb91a3735a',
  'Merchant Name': 'Trivedi Ltd',
  'Merchant Category Code (MCC)': 3044,
  'Transaction Location (City or ZIP Code)': 'Lucknow',
  'Transaction Currency': 'EUR',
  'Card Type': 'MasterCard',
  'Card Expiration Date': '11/32',
  'CVV Code (Hashed or Encrypted)': 'df56bc061e91023bff33c6ba0d49d166a60e3aa9317f90e7a7fa3d7a65f96886',
  'Transaction Response Code': 12,
  'Transaction ID': '9ea4049e-7e03-47cf-8e5b-480ff3ddc2d8',
  'Fraud Flag or Label': 1,
  'Previous Transactions': '2',
  'Transaction Source': 'In-Person',
  'IP Address': '129.152.88.127',
  'Device Information': 'Tablet',
  'User Account Information': 'samaira88',
  'Transaction Notes': 'Quia perferendis veniam adipisci esse voluptas eius nesciunt. Incidunt fuga aliquam itaque. Eaque amet rerum beatae.'},
 {'Transaction Date and Time': '2022-10-30 11:43:18',
  'Transaction Amount': 4146.54,
  'Cardholder Name': 'Suhana Thaker',
  'Card Number (Hashed or Encrypted)': 'cb6afb02740fdedd33011ceed39a65b069c766a1e555b7a4eaf73053342ea91c',
  'Merchant Name': 'Golla Ltd',
  'Merchant Category Code (MCC)': 8041,
  'Transaction Location (City or ZIP Code)': 'Bareilly',
  'Transaction Currency': 'USD',
  'Card Type': 'American Express',
  'Card Expiration Date': '11/27',
  'CVV Code (Hashed or Encrypted)': '3097fc802d49355a0a256d4b07ab9f7257fcf35077cdb8133d59f607fedb229e',
  'Transaction Response Code': 0,
  'Transaction ID': 'cef27823-3227-4b51-9466-18dd0cbe0cfa',
  'Fraud Flag or Label': 0,
  'Previous Transactions': '3 or more',
  'Transaction Source': 'In-Person',
  'IP Address': '87.218.105.217',
  'Device Information': 'Mobile',
  'User Account Information': 'aniruddh46',
  'Transaction Notes': 'Aspernatur temporibus ducimus pariatur. Modi qui voluptatibus adipisci aliquid rem doloremque. Facere minima culpa voluptas.'},
 {'Transaction Date and Time': '2022-08-02 00:47:58',
  'Transaction Amount': 4088.07,
  'Cardholder Name': 'Onkar Dhingra',
  'Card Number (Hashed or Encrypted)': '625636f8fe24cd4d75f955fa5897284e25ff19e84b1669f60a28091bccda3e58',
  'Merchant Name': 'Sem, Bhatia and Kala',
  'Merchant Category Code (MCC)': 2206,
  'Transaction Location (City or ZIP Code)': 'Muzaffarpur',
  'Transaction Currency': 'USD',
  'Card Type': 'American Express',
  'Card Expiration Date': '08/29',
  'CVV Code (Hashed or Encrypted)': '79bf08685d3138f9b109c3546780f056bc954fd69377b84a2cf23622e464897b',
  'Transaction Response Code': 0,
  'Transaction ID': 'e0b2549b-5f4f-4e97-b8e5-ef17ce4dbf32',
  'Fraud Flag or Label': 1,
  'Previous Transactions': nan,
  'Transaction Source': 'In-Person',
  'IP Address': '220.44.41.155',
  'Device Information': 'Mobile',
  'User Account Information': nan,
  'Transaction Notes': 'Amet accusamus impedit voluptatum omnis. Ab fugit inventore nihil cupiditate nostrum illum alias. Minima aspernatur laborum.'},
 {'Transaction Date and Time': '2020-04-07 04:49:24',
  'Transaction Amount': 4484.69,
  'Cardholder Name': 'Nayantara Agarwal',
  'Card Number (Hashed or Encrypted)': 'b40ed568c9bb7d8009e856ae0edcc5cb9f3fc0f5a241ac4916b8b87487ad9d1f',
  'Merchant Name': 'D’Alia-Dhingra',
  'Merchant Category Code (MCC)': 6957,

In [ ]:
cols

('Transaction Date and Time',
 'Transaction Amount',
 'Cardholder Name',
 'Card Number (Hashed or Encrypted)',
 'Merchant Name',
 'Merchant Category Code (MCC)',
 'Transaction Location (City or ZIP Code)',
 'Transaction Currency',
 'Card Type',
 'Card Expiration Date',
 'CVV Code (Hashed or Encrypted)',
 'Transaction Response Code',
 'Transaction ID',
 'Fraud Flag or Label',
 'Previous Transactions',
 'Transaction Source',
 'IP Address',
 'Device Information',
 'User Account Information',
 'Transaction Notes')

**Compute the average of your chosen field for the filtered subset, using only sum() and len().**

In [ ]:
mask1=[]
for i in named_red:
   mask1.append(i['Transaction Amount'])
sum=0
for i in mask1:
  sum+=i
avg=sum/len(mask1)
avg


np.average(mask1)

np.float64(2496.3560362499998)

**Build a boolean mask — a list of True/False values, one per record — using a list comprehension.**

In [ ]:
mask=[]
for i in named_red:
   mask.append(i['Transaction Amount']>1500)

mask[::1000]

[False, True, True, True, False, True, False, False]

In [ ]:
mask_comprehension = [record_dict['Transaction Amount'] > 1500 for record_dict in named_red]

display(mask_comprehension[::1000])

[False, True, True, True, False, True, False, False]

# **Task 5 — Build your feature matrix X and target vector y  (Stretch)**

Choose 3 numeric fields from your dataset to form X.
Choose one categorical field to become your binary label y (encode it as 1/0).
Build X as a list of lists, and y as a list of integers, using list comprehensions.
Print X[0] and y[0] to verify.
Bonus: count how many positive cases (y=1) exist in your dataset.

In [ ]:


X = [
    [record['Transaction Amount'], record['Merchant Category Code (MCC)'], record['Transaction Response Code']]
    for record in named_red
]



y = [
    record['Fraud Flag or Label']
    for record in named_red
]

print("First 5 entries of X:")
print(X[:5])
print("\nLength of X:", len(X))

print("\nFirst 5 entries of y:")
print(y[:5])
print("\nLength of y:", len(y))

First 5 entries of X:
[[285.88, 3590, 5], [1777.32, 7277, 12], [3939.01, 9297, 5], [376.44, 5686, 5], [1687.33, 2940, 5]]

Length of X: 8000

First 5 entries of y:
[1, 1, 1, 0, 1]

Length of y: 8000

In [ ]:
print("X[0]:", X[0])
print("y[0]:", y[0])

In [ ]:
positive_cases = __builtins__.sum(1 for label in y if label == 1)

print(f"Number of positive cases (y=1): {positive_cases}")

Number of positive cases (y=1): 3989

# **Task 6 — Wrap it in a function (Functions)**

In [ ]:
def build_xy_matrices(records_list):
    """
    Builds the feature matrix X and target vector y for machine learning.

    X consists of 'Transaction Amount', 'Merchant Category Code (MCC)', and 'Transaction Response Code'.
    y consists of 'Fraud Flag or Label' (binary encoded).

    Args:
        records_list (list): A list of dictionaries, where each dictionary represents a record
                             and contains relevant fields.

    Returns:
        tuple: A tuple containing:
            - X (list of lists): The 2D feature matrix.
            - y (list of ints): The 1D binary target vector.
    """
    X = [
        [record['Transaction Amount'], record['Merchant Category Code (MCC)'], record['Transaction Response Code']]
        for record in records_list
    ]

    y = [
        record['Fraud Flag or Label']
        for record in records_list
    ]

    return X, y

X_new, y_new = build_xy_matrices(named_red)

print("First 5 entries of X_new (from function):")
print(X_new[:5])
print("\nLength of X_new:", len(X_new))

print("\nFirst 5 entries of y_new (from function):")
print(y_new[:5])
print("\nLength of y_new:", len(y_new))

First 5 entries of X_new (from function):
[[285.88, 3590, 5], [1777.32, 7277, 12], [3939.01, 9297, 5], [376.44, 5686, 5], [1687.33, 2940, 5]]

Length of X_new: 8000

First 5 entries of y_new (from function):
[1, 1, 1, 0, 1]

Length of y_new: 8000

# ** Why did you choose tuples (not lists) for your individual records?**




**Immutability**: Tuples are immutable, meaning their contents cannot be changed after creation.  Once a record is extracted, you know its values won't change.

---


**Read Named Fields**: namedtuple allows you to access fields by name (e.g., record.TransactionAmount) in addition to their index (e.g., record._1).

---


**Efficiency**: Tuples are generally more memory-efficient and slightly faster than lists, especially when dealing with a large number of fixed-size records.

---


**Use as Dictionary Keys**: Because tuples are immutable, they can be used as keys in dictionaries, which lists cannot be.

# ** What field in your dataset would be risky to access by position (r[3]) instead of by name? Why?**


Accessing fields by position (like r[3]) is risky because the order of columns can change. If columns are added, removed, or reordered in the dataset, r[3] would then refer to a completely different field, or cause an error if the index no longer exists or the data type is incompatible.

For example, the field 'Card Number is currently at index 3 If a new column were inserted before it, or an existing column before it was removed, then r[3] would refer to entire diff colums

**From your DataCamp course: which of the four pandas row-iteration methods (iloc, iterrows, itertuples, apply) would you guess is fastest for processing all your records — and why might that connect to what you built in Task 1-3 today?**


---



**itertuples()**: This method returns an iterator that yields namedtuple objects (or regular tuples if index=False and name is None) for each row. namedtuple objects are much more lightweight and efficient than pandas Series objects, which iterrows yields. This significantly reduces overhead, making itertuples much faster.
iloc: iloc is primarily for integer-location based indexing to select subsets of data, not for iterating over rows efficiently. While you can loop through df.iloc[i] for each i, it's not optimized for full row-wise iteration.


---


**iterrows()**: This method yields (index, Series) pairs for each row. The constant creation of a new pandas Series object for each row is computationally expensive, making it generally the slowest method for row iteration.


---


**apply()**: The speed of apply() depends heavily on the function being applied. If the function can be vectorized (i.e., operates on entire columns at once), apply() can be very fast. However, if apply() is used with a function that processes each row individually, it often performs similarly to or worse than iterrows() because it still involves Python-level iteration and object creation overhead, though it can be slightly better due to some internal optimizations compared to explicit Python loops.